### ISSUE TITLE
Failed! (Wrong MIME) when logged in

### ISSUE THREAD

**Issue by davidtabernerom** [ccloli/E-Hentai-Downloader#104]
Title says it all: if you try to download all archive without logging in, everything is ok:
![imagen](https://user-images.githubusercontent.com/16870364/39654368-c4dbce3a-4ff4-11e8-8efc-12f3f3cf0606.png)

But when you log in to download the High-Res ones, a Wrong-MIME-type error comes out: 
![imagen](https://user-images.githubusercontent.com/16870364/39654235-62bf7378-4ff4-11e8-9839-98decdfbfb0b.png)

**Comment by ccloli** [comment]
Hi, it works fine here. Maybe it's due to your cookie is not sync with E-Hentai forum. Please try this link https://e-hentai.org/s/47c35e94f1/1219746-1 , and you'll see the link `Download original 860 x 1214 564.9 KB source` at the bottom of the page, click that link and it'll redirect you to the login page.

If it gives you the image file, or redirect in a loop, please make sure that you've enabled cookie and also accept third-party cookie (#86 (comment) says that if you don't enable third-party cookie, it may have some problems to download).

If you still get the message, please try clearing your cookie and try again. If it doesn't work, please press `F12`, choose Console tab, and copy all the logs that started with `[EHD]` then paste them here.

**Comment by davidtabernerom** [comment]
Hi, tried doing a full clean for cookies and stuff, and tried again with the link you provided, results are even stranger.
Happens the same, but this time, there are 2 images that has been able to download:
![imagen](https://user-images.githubusercontent.com/16870364/39662377-e97c0a86-5060-11e8-96fc-b0bdc13fe5d3.png)

[Here](https://davidtabernero.net/firefox.log.txt) you have the full log as requested.

**Comment by ccloli** [comment]
Seems that you're using Firefox, so I tested it on Firefox again, and everything is fine. I try accessing the original image link without login, and the result is similar to the log you provided.

The response headers in your log is 734~735 bytes, content type is `text/html`, and it's just the same as the size of redirect login page. So maybe you should check your browser Cookies configuration, make sure you've enabled **Accept cookies from websites** and **Accept third-party cookies**, for detailed steps you can check https://github.com/ccloli/E-Hentai-Downloader/issues/92#issuecomment-359184675 . 

![qq 20180505194947](https://user-images.githubusercontent.com/8115912/39663057-ced6b5f8-509e-11e8-9003-21169c9ba0a7.png)

If you've cleared your cookies, enabled all cookie policies or whitelisted `e-hentai.org` but still have the bug, please let me know.

**Comment by davidtabernerom** [comment]
Ok, I just made a backup of my current Firefox profile and reset Firefox fresh, and everything is now working.
Cookies are already enabled even for third parties, so doesn't seem to be the problem.
I will keep investigating until found it, but everything seems working now.
