### ISSUE TITLE
Download only same number of pictures

### ISSUE THREAD

**Issue by Teriop** [ccloli/E-Hentai-Downloader#112]
Download only same number of pictures as point out in "Download * images in same time". After downloading same number download is stop.

Sorry for my English.

**Comment by Teriop** [comment]
And I cleaned cookies, it is't help.

**Comment by Teriop** [comment]
На русском?

Закачивает только такое же количество картинок, что и указано в графе "Одновременно закачивать картинок". После этого новые картинки не загружаются (не появляются в очереди), архив не скачиваается.

**Comment by Teriop** [comment]
Firefox 56 Greasemonkey 4.1 and Firefox 60 GM 4.4.

But

I delete on firefox 56 Greasemonkey and install 3.17 version and trouble is gone!

But on Firefox 60 it can't be installed!

Information from Firefox 60

[EHD] E-Hentai Downloader is running.
E-Hentai%20Downloader:524:1
[EHD] Bugs Report > https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback
E-Hentai%20Downloader:525:1
[EHD] To report a bug, it's recommended to provide the logs started with "[EHD]", thanks. =w=
E-Hentai%20Downloader:526:1
[EHD] UserAgent > Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
E-Hentai%20Downloader:12553:1
[EHD] Script Handler > Greasemonkey
E-Hentai%20Downloader:12554:1
[EHD] Script Handler Version > 4.4.0
E-Hentai%20Downloader:12555:1
[EHD] E-Hentai Downloader Version > 1.30.2
E-Hentai%20Downloader:12556:1
[EHD] Current URL > https://exhentai.org/g/1185998/0f4002f7d4/
E-Hentai%20Downloader:12557:1
[EHD] Is Logged In > true
E-Hentai%20Downloader:12558:1
[EHD] E-Hentai Downloader Setting > {"save-info-list":["title","metas","uploader-comment","page-links"]}
E-Hentai%20Downloader:12520:3
[EHD] Request Image Limits From e-hentai.org
E-Hentai%20Downloader:14507:2
[EHD] Index > 4  | RealIndex > 4  | Name > wm05.jpg  | RetryCount > 0  | DownloadedCount > 1  | FetchCount > 5  | FailedCount > 0
E-Hentai%20Downloader:12688:2
[EHD] Index > 1  | RealIndex > 1  | Name > wm01.jpg  | RetryCount > 0  | DownloadedCount > 2  | FetchCount > 5  | FailedCount > 0
E-Hentai%20Downloader:12688:2
[EHD] Index > 2  | RealIndex > 2  | Name > wm03.jpg  | RetryCount > 0  | DownloadedCount > 3  | FetchCount > 5  | FailedCount > 0
E-Hentai%20Downloader:12688:2
[EHD] Index > 3  | RealIndex > 3  | Name > wm04.jpg  | RetryCount > 0  | DownloadedCount > 4  | FetchCount > 5  | FailedCount > 0
E-Hentai%20Downloader:12688:2
[EHD] Index > 5  | RealIndex > 5  | Name > wm06.jpg  | RetryCount > 0  | DownloadedCount > 5  | FetchCount > 5  | FailedCount > 0
E-Hentai%20Downloader:12688:2
[EHD] Request Image Limits From e-hentai.org
E-Hentai%20Downloader:14507:2


https://d.radikal.ru/d30/1806/b9/e4a6c4d032f3.png


I tried download with Pages Range but result was same.

**Comment by GioRixxx** [comment]
Same problem here. I managed to get bypass the problem setting to download 999 images at the same time and giving it a 1s delay (5th option in settings) instead of the five base pictures.
However, this doesn't really solve the problem. I'm running firefox 61.0.1 x64, greasemonkey 4.5, no adblocker enabled on exhentai, nor other plugins that could enter in cofnlict (tried to disable all of them too, obv). No other script either.
Changing the delay doesen't do anything by itself, i kinda did it to avoid to make strange traffic.
So, the issue stays probably in the limit of images downloaded at the same time. The stats box doesn't give any error message, it just stay stuck as in the attached pic (still alive tho, buttons and scroll works fine so the script doesn't seem to have crashed).
Hope I've been clear, I'm no mother tongue either so there could be some errors here and there. If you miss some point just ask me and I'll try to explain it better.

![cattura](https://user-images.githubusercontent.com/32719982/42420824-26af1fc2-82cc-11e8-8a46-922d7cca988a.PNG)

**Comment by ccloli** [comment]
Sorry I'm a little busy these days, so I forgot to reply you issues.

Another issue at [GreasyFork#39910](https://greasyfork.org/zh-CN/forum/discussion/39910/x) says 1.30.1 works fine, and I have no time to check what's up these days, so I revert some changes between 1.30.1 and 1.30.2 and release a new version 1.30.3 so that you can use the older version to download. But if it doesn't work, please let me know.

**Comment by GioRixxx** [comment]
1.30.3 works fine, thanks.
