### ISSUE TITLE
Files can't be generated

### ISSUE THREAD

**Issue by psc2350** [ccloli/E-Hentai-Downloader#120]
https://exhentai.org/g/1106338/8fa4ed2948/
I like it how e-hentai downloader can automatically zip the files with compression preference.
I can read the zip files with Massigra flawless with 0 compression.
However, it seems like galleries that are too big in file size have an issue to zip.
Is it possible to simply save the images of these non-zippable galleries in series to a desire folder, so the user may at least get the images and zip it themselves.

**Comment by ccloli** [comment]
Looks like the gallery is too large, you should try downloading with torrent if available.

It's not possible to download them to a specific directory in local file system directly due to browser security limit, that's why we need to package them to a zip file. If you want to download them to a folder, you should try some other tools.

If you still want to download it with the script, you should try setting _Pages Range_ to download them to multiple smaller part (like setting it to `0-200`, `201-400`, `401-600`... to download 200 images in each time). But you should have a look at [File Size Limit](https://github.com/ccloli/E-Hentai-Downloader#file-size-limit) section to make sure the size of each part doesn't exceed the limit.

Here is an example that I download a 1 GB gallery, I set _Pages Range_ to `1-130`, `131-262`, `263-` to get 3 zip files, each one has about 130 images, around 350 MB (forget the `149` zip, the image is not downloaded due to a bug, and it's fixed in previous version).

![image](https://user-images.githubusercontent.com/8115912/48149491-29bf4300-e2f7-11e8-8d96-023a0323cd5b.png)
