### ISSUE TITLE
本本超過2GB 會無法下載

### ISSUE THREAD

**Issue by MIYANLIDO** [ccloli/E-Hentai-Downloader#168]
單本超過2GB 常常已下載完 但會卡在要準備轉成ZIP檔時 就不會轉成ZIP下載

https://upload.cc/i1/2020/07/17/V4F90X.png

https://upload.cc/i1/2020/07/17/EzAC67.png

請問 這要如何解決???

**Comment by ccloli** [comment]
簡單來說，這是由於下載的檔案過大，導致遊覽器內存溢出，最終導致腳本出錯

在 GreasyFork 上同樣有人提出了這個問題：https://greasyfork.org/zh-CN/scripts/10379-e-hentai-downloader/discussions/5045

現階段沒有比較好的解決方法，建議藉助「Pages Range」功能指定需要下載的頁碼區間，然後分次下載，即便內存很大建議預估文件大小也不要超過 500MB

或者更好的方法是尋找其他的工具，一般的 CLI 程式或者原生應用不會受到遊覽器限制

**Comment by TestPolygon** [comment]
What about is just to split to chunks (500 MB) the result archive while you are downloading?

Also: https://github.com/jimmywarting/StreamSaver.js

**Comment by ccloli** [comment]
> What about is just to split to chunks (500 MB) the result archive while you are downloading?

It has been discussed on #57, some problems are not resolved, like:

1. If some files are failed, is this part of zip file need to wait them to retry? Or just skip them?
2. Will the zip file be generated when they're ready, or all of the downloads are finished? The first one is a better solution, since if the file is ready, these data can be dropped. But if that part of zip file is not saved to local disk like clicking the cancel button? The script doesn't know user's action.

> Also: https://github.com/jimmywarting/StreamSaver.js

Streams API is a good way to fix some problem (mostly used out of memory), in fact I wrote an [article](https://github.com/x-orpheus/blog/blob/master/content/blog/streams-api/index.md#%E4%B8%8B%E8%BD%BD%E4%B8%80%E4%B8%AA%E5%89%8D%E7%AB%AF%E7%94%9F%E6%88%90%E7%9A%84%E5%A4%A7%E6%96%87%E4%BB%B6) (in Chinese) about how Streams API works, and use E-Hentai Downloader as an example to show a possible way.

https://p1.music.126.net/gwXd1UARwddTyHxKszIOwg==/109951164511678870.png

However, there are still some questions to be solved:

1. Download file via Streams API requires Service Worker, and Service Worker needs to install on an HTTPS site. This problem should be solved, about one and a half years ago, E-Hentai isn't using HTTPS.
2. To install a Service Worker, you need to install the script from an exist URL on a server, and cannot be installed from a base64 URL or blob URL. So the Service Worker script needs to be hosted on a stable server and needs to resolve some CORS problem. Also I'm not sure is this allowed on GreasyFork.
3. The Service Worker runs as a middle man between the client and the server, it may handles ALL the network traffic. So it needs to process all the request correctly, or it may breaks the site.

As I'm not focus on it for not, though I have some ideas, I haven't try it yet, so I'm not sure if it work. The feature may be in v2, however I'm not having much time to work on it, so...

**Comment by TestPolygon** [comment]
You do not need to install the service worker to e-x site. You need only SW installed on Github Pages.

For example:
https://testpolygon.github.io/stream-saver-fetch/

Main origin: https://testpolygon.github.io
File to download origin: https://d8d913s460fub.cloudfront.net
Iframe with installed SW origin: https://jimmywarting.github.io


Site -> message(s) to iframe with installed SW -> downloading from fake iframe's origin.

**Comment by ccloli** [comment]
Yes, using iframe is a workaround to use StreamSaver.js, though I'm not sure why your demo is not working from my side, showing `Failed to load resource: the server responded with a status of 404 () (jimmywarting.github.io/StreamSaver.js/testpolygon.github.io/764996/cat.mp4:1)`, and it seems that the Service Worker has been installed. Also it should be noted that it requires to access to an external site, and that site should be accessible from users, not only the site is not down, but also not blocked (if you're in China, you know what I'm talking about, and that's the reason why E-Hentai Downloader choose to bundle the libraries instead of require them from a CDN). 

Use StreamSaver.js to save file is fine, however it may not fix this issue. I cannot access to the images the author posts (it's blocked by CloudFlare from my side, saying `This website is using a security service to protect itself from online attacks.`), but I guess it may be the same issue from https://greasyfork.org/zh-CN/scripts/10379-e-hentai-downloader/discussions/5045 . The thread says he has 384 GB RAM, but when downloading a 2.2 GB gallery, it stucks at `Calculating extra data...`. By reviewing the source code, the error may caused when JSZip is generating the zip file. So the error may happens inside the JSZip library, and not sure using `generateInternalSteam()` and SteamSaver.js can solve the problem (it might be, since the bug may due to cannot allocate more ArrayBuffer to store data). Will write a demo to check if it works, but since I'm too busy these days and have no spare energy to deal with it, so it may take some time.

**Comment by TestPolygon** [comment]
About demo: 
I have specially modified the demo and added the input.
The another example of URL: https://i.imgur.com/KWvtdg0.mp4 (Or any other with CORS allowed)
For the best representation use:
![Screenshot](https://user-images.githubusercontent.com/38364068/89124060-c3238500-d4dc-11ea-9d7c-00251b3cb96d.png)
Also I uncommented loading `web-streams-polyfill` script, it's required by Firefox.

> https://greasyfork.org/zh-CN/scripts/10379-e-hentai-downloader/discussions/5045

404 for me.

**Comment by ccloli** [comment]
Okay, I enabled "Bypass for network" in Devtools, so in fact the download URL is not handled by Service Worker.

> 404 for me.

You can try https://sleazyfork.org/zh-CN/scripts/10379-e-hentai-downloader/discussions/5045 , though it says in Chinese. In short:

> The thread says he has 384 GB RAM, but when downloading a 2.2 GB gallery, it stucks at `Calculating extra data...`. By reviewing the source code, the error may caused when JSZip is generating the zip file. 

> BTW, the newer versions of JSZip have the performance bug:

Yes, since that thread shows the error throws from JSZip, so I upgraded JSZip from 3.1.5 to 3.5.0, then #164 said that the packaging speed is slower than before, so I rolled it back to 3.1.5.

**Comment by ccloli** [comment]
此問題已嘗試在 v1.33 中改進，但需要 Chrome 瀏覽器且需要開啟 File System，請在 _Settings_ -> _Advanced_ -> _Use File System to handle large Zip file_ 中開啟它。根據我在 #182 的測試，下載了一個 2.31 GB 大小的畫集沒有問題。

***

This problem should be improved in v1.33, but it requires Chrome and enable File System, please enable it at _Settings_ -> _Advanced_ -> _Use File System to handle large Zip file_. From my test on #182, it works well with a 2.31 GB gallery.

> v1.33 is released just now, and it's optimized for File System (and also fixes some GC problem), so it won't wait until the zip file is completed and won't eat double RAM when generating the zip file. If you have enough RAM, you can download this gallery without any problem now. But please note that it still takes your RAM to store images, so it still needs about 2+GB RAM.

***

@TestPolygon Well, the latest version doesn't use StreamSaver.js, and it's not the problem. From my searching on JSZip's issues, [some issues](https://github.com/Stuk/jszip/issues?q=2GB) also said that they cannot handle some zip file which is larger than 2 GB, so I think it's JavaScript runtime limitation. All the 3 issue doesn't post any logs, only settings and/or progress dialog, so I cannot determine what's up, and only to guess, well, it's a RAM limitation, but it's not.

The solution is just like yours, but instead of using StreamSaver.js (it may still be added in the future), it use File System API. In fact the feature is already in script, but not optimized for JSZip 3.0.0+ which uses async and stream-like api. It uses the same way as default Blob storage, generate zip file with `zip.generateAsync()`, wait until it returns the result, slice it and writes to File System, then request to download from File System. And the 2 GB limitation occurs at waiting result, since JSZip needs to handle previous chunks and merge new chunks.

v1.33 optimizes File System solution with JSZip stream-like api. This time it generates file with `zip.generateInternalStream()` which is a `StreamHelper`, and it sends data by chunks. Since File System also writes file as chunk, so we just need to pass the chunk data to File System, just like working with Streams API (or say StreamSaver.js). This bypass the 2 GB limitation as these chunks will be garbage collected after writing to File System, and also reduce the memory usage. Compared with Blob storage or old way, instead of eating DOUBLE size of RAM, it just take the same size as gallery size (+ chunk buffer size) of RAM.
