### ISSUE TITLE
archive file name as URL

### ISSUE THREAD

**Issue by gin9980** [ccloli/E-Hentai-Downloader#170]
I use Calibre for my archives with a customized plugin that perfectly fetches metadata if you have the title name as a URL instead.

Could there be an added option for the downloader to instead grab the URL such as "https://e-hentai.org/g/1709342/04f30ea79e/" instead of "[Takanashi Ringo] Cynical Dog [English] [Digital]" into the archive file name instead? Since the URL contains special characters such as ":" and "/" the downloader plugin can convert those characters to "q" and "l" instead to make "httpsqlle-hentai.orglgl1709342l04f30ea79el" where I can use regex to convert it back in Calibre then fetch the metadata without any errors. 
Or make make an option where the archive name is the end of the URL such as "1709342 04f30ea79e" then I can use regex as well to convert to a full URL.

Would be greatly helpful as I really like Calibre more than the other alternatives due to the vast features and customizablilty it provides.

**Comment by yingziwu** [comment]
I think you need Calibre plugin.
https://blog.bgme.me/posts/use-calibre-to-manage-your-doujinshi-2/

**Comment by yingziwu** [comment]
Besides, the plugin mention above need to do some modifications, such as add proxy support, change match rule to fix e-hentai new interview.

**Comment by gin9980** [comment]
> 
> 
> I think you need Calibre plugin.
> https://blog.bgme.me/posts/use-calibre-to-manage-your-doujinshi-2/
> 
> Besides, the plugin mention above need to do some modifications, such as add proxy support, update match rule to fit e-hentai new interview.

that the one I use, it can fetch metadata but not accuratly without the use of URL names

**Comment by ccloli** [comment]
Actually, you can set zip name on _Settings_ as `httpsqlle-hentai.orglgl{gid}|{token}l` if you like.
---原始邮件---
发件人:&quot;CRft20&quot;<notifications@github.com&gt;
发送时间:2020年8月18日 星期二 上午3:36
收件人:&quot;ccloli/E-Hentai-Downloader&quot;<E-Hentai-Downloader@noreply.github.com&gt;
抄送:&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;
主题:[ccloli/E-Hentai-Downloader] archive file name as URL (#170)



I&nbsp;use&nbsp;Calibre&nbsp;for&nbsp;my&nbsp;archives&nbsp;with&nbsp;a&nbsp;plugin&nbsp;that&nbsp;perfectly&nbsp;fetches&nbsp;metadata&nbsp;if&nbsp;you&nbsp;have&nbsp;the&nbsp;title&nbsp;name&nbsp;as&nbsp;a&nbsp;URL&nbsp;instead.

Could&nbsp;there&nbsp;be&nbsp;an&nbsp;added&nbsp;option&nbsp;for&nbsp;the&nbsp;downloader&nbsp;to&nbsp;instead&nbsp;grab&nbsp;the&nbsp;URL&nbsp;such&nbsp;as&nbsp;&quot;https://e-hentai.org/g/1709342/04f30ea79e/&quot;&nbsp;instead&nbsp;of&nbsp;&quot;[Takanashi&nbsp;Ringo]&nbsp;Cynical&nbsp;Dog&nbsp;[English]&nbsp;[Digital]&quot;&nbsp;into&nbsp;the&nbsp;archive&nbsp;file&nbsp;name&nbsp;instead?&nbsp;Since&nbsp;the&nbsp;URL&nbsp;contains&nbsp;special&nbsp;characters&nbsp;such&nbsp;as&nbsp;&quot;:&quot;&nbsp;and&nbsp;&quot;/&quot;&nbsp;the&nbsp;downloader&nbsp;plugin&nbsp;can&nbsp;convert&nbsp;those&nbsp;characters&nbsp;to&nbsp;&quot;q&quot;&nbsp;and&nbsp;&quot;l&quot;&nbsp;instead&nbsp;to&nbsp;make&nbsp;&quot;httpsqlle-hentai.orglgl1709342l04f30ea79el&quot;&nbsp;where&nbsp;I&nbsp;can&nbsp;use&nbsp;regex&nbsp;to&nbsp;convert&nbsp;it&nbsp;back&nbsp;in&nbsp;Calibre&nbsp;then&nbsp;fetch&nbsp;the&nbsp;metadata&nbsp;without&nbsp;any&nbsp;errors.

Would&nbsp;be&nbsp;greatly&nbsp;helpful&nbsp;as&nbsp;I&nbsp;really&nbsp;like&nbsp;Calibre&nbsp;more&nbsp;than&nbsp;the&nbsp;other&nbsp;alternatives&nbsp;due&nbsp;to&nbsp;the&nbsp;vast&nbsp;features&nbsp;and&nbsp;customizablilty&nbsp;it&nbsp;provides.

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;are&nbsp;subscribed&nbsp;to&nbsp;this&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by gin9980** [comment]
> 
> Actually, you can set zip name on _Settings_ as `httpsqlle-hentai.orglgl{gid}|{token}l` if you like. ---原始邮件--- 发件人:&quot;CRft20&quot;<notifications@github.com&gt; 发送时间:2020年8月18日 星期二 上午3:36 收件人:&quot;ccloli/E-Hentai-Downloader&quot;<E-Hentai-Downloader@noreply.github.com&gt; 抄送:&quot;Subscribed&quot;<subscribed@noreply.github.com&gt; 主题:[ccloli/E-Hentai-Downloader] archive file name as URL (#170) I&nbsp;use&nbsp;Calibre&nbsp;for&nbsp;my&nbsp;archives&nbsp;with&nbsp;a&nbsp;plugin&nbsp;that&nbsp;perfectly&nbsp;fetches&nbsp;metadata&nbsp;if&nbsp;you&nbsp;have&nbsp;the&nbsp;title&nbsp;name&nbsp;as&nbsp;a&nbsp;URL&nbsp;instead. Could&nbsp;there&nbsp;be&nbsp;an&nbsp;added&nbsp;option&nbsp;for&nbsp;the&nbsp;downloader&nbsp;to&nbsp;instead&nbsp;grab&nbsp;the&nbsp;URL&nbsp;such&nbsp;as&nbsp;&quot;[https://e-hentai.org/g/1709342/04f30ea79e/&quot;&nbsp;instead&nbsp;of&nbsp;&quot;[Takanashi&nbsp;Ringo]&nbsp;Cynical&nbsp;Dog&nbsp;[English]&nbsp;[Digital]&quot;&nbsp;into&nbsp;the&nbsp;archive&nbsp;file&nbsp;name&nbsp;instead?&nbsp;Since&nbsp;the&nbsp;URL&nbsp;contains&nbsp;special&nbsp;characters&nbsp;such&nbsp;as&nbsp;&quot;:&quot;&nbsp;and&nbsp;&quot;/&quot;&nbsp;the&nbsp;downloader&nbsp;plugin&nbsp;can&nbsp;convert&nbsp;those&nbsp;characters&nbsp;to&nbsp;&quot;q&quot;&nbsp;and&nbsp;&quot;l&quot;&nbsp;instead&nbsp;to&nbsp;make&nbsp;&quot;httpsqlle-hentai.orglgl1709342l04f30ea79el&quot;&nbsp;where&nbsp;I&nbsp;can&nbsp;use&nbsp;regex&nbsp;to&nbsp;convert&nbsp;it&nbsp;back&nbsp;in&nbsp;Calibre&nbsp;then&nbsp;fetch&nbsp;the&nbsp;metadata&nbsp;without&nbsp;any&nbsp;errors](https://e-hentai.org/g/1709342/04f30ea79e/&quot;&nbsp;instead&nbsp;of&nbsp;&quot;%5BTakanashi&nbsp;Ringo%5D&nbsp;Cynical&nbsp;Dog&nbsp;%5BEnglish%5D&nbsp;%5BDigital%5D&quot;&nbsp;into&nbsp;the&nbsp;archive&nbsp;file&nbsp;name&nbsp;instead?&nbsp;Since&nbsp;the&nbsp;URL&nbsp;contains&nbsp;special&nbsp;characters&nbsp;such&nbsp;as&nbsp;&quot;:&quot;&nbsp;and&nbsp;&quot;/&quot;&nbsp;the&nbsp;downloader&nbsp;plugin&nbsp;can&nbsp;convert&nbsp;those&nbsp;characters&nbsp;to&nbsp;&quot;q&quot;&nbsp;and&nbsp;&quot;l&quot;&nbsp;instead&nbsp;to&nbsp;make&nbsp;&quot;httpsqlle-hentai.orglgl1709342l04f30ea79el&quot;&nbsp;where&nbsp;I&nbsp;can&nbsp;use&nbsp;regex&nbsp;to&nbsp;convert&nbsp;it&nbsp;back&nbsp;in&nbsp;Calibre&nbsp;then&nbsp;fetch&nbsp;the&nbsp;metadata&nbsp;without&nbsp;any&nbsp;errors). Would&nbsp;be&nbsp;greatly&nbsp;helpful&nbsp;as&nbsp;I&nbsp;really&nbsp;like&nbsp;Calibre&nbsp;more&nbsp;than&nbsp;the&nbsp;other&nbsp;alternatives&nbsp;due&nbsp;to&nbsp;the&nbsp;vast&nbsp;features&nbsp;and&nbsp;customizablilty&nbsp;it&nbsp;provides. &mdash; You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;are&nbsp;subscribed&nbsp;to&nbsp;this&nbsp;thread. Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

thanks, much appriciated. Didn't know it could already do this.
