### ISSUE TITLE
version 1.32.1 break on firefox 74.0.1

### ISSUE THREAD

**Issue by karasawa-user** [ccloli/E-Hentai-Downloader#173]
Rolling back to 1.31.11 because the new version now just do literally nothing on any galleries and seems setting won't be stored as all option remain unchecked after save. Deleting cookie seems didn't work either and while reinstalling still remain same even though this time I could save the option
I still don't want to use tampermonkey or violentmonkey either because they made unnecessary extra load and run slower than greasemonkey

**Comment by prysme01** [comment]
Same here, rolling back to 1.31.11

**Comment by ccloli** [comment]
The bug will be fixed ASAP, but before then, let me explain what's up in recent changes.

#172 reports that `v1.31.11` is not working on Firefox with GreaseMonkey and this bug can also be reproduced from my side. The bug is due to GreaseMonkey 4.x provides some function for 3.x and has been replaced in 4.x, so the compact code is not running.

To fix the bug, `v1.31.12` is released, but #172 still reports that the cookies is not passed when downloading images. It's a long tern bug that most of them are happened on Firefox, and some of them mentioned that they're using GreaseMonkey.

So `v1.32` adds a feature that the script will pass the cookies to the download request manually, which fixes #172. Then [an issue](https://greasyfork.org/zh-CN/scripts/10379-e-hentai-downloader/discussions/61837) on GreasyFork said that the newer version is not working on GreaseMonkey 3.11. The reason I cannot explain well, but I've met it when GreaseMonkey 4.x release, so a safer way is to change to the old method, and stick the compact code to only GreaseMonkey.

Then `v1.32.1` is come out, and the user reported on GreasyFork said it's working again. Then a few hours later, you said it's break on GreaseMonkey again...

![image](https://user-images.githubusercontent.com/8115912/92489363-48a7fc80-f222-11ea-8aaa-09bdd832b369.png)

**Comment by ccloli** [comment]
BTW, is that ALL versions between `v1.32.11` and `v.1.32.1` are not working?

Also @snthsnthsnthsnth are you also experience the same problem on `v1.32.1`?

**Comment by snthsnthsnthsnth** [comment]
v1.32.1 still needs manual cookie passing for full sized images. Running with TamperMonkey.

**Comment by ccloli** [comment]
`v1.32.2` is released, it should fix the bug that GreaseMonkey 4.x is not working.

Why it happens?

> so a safer way is to change to the old method, and stick the compact code to only GreaseMonkey

Userscript has an API `GM_info`, which has a field named `scriptHandler`, it should returns the name of the userscript extension. So to fix the previous 3.x bug, the script compares it with string `GreaseMonkey`, and it works.

But why GreaseMonkey 4.x is not working?

Well, in GreaseMonkey 3.x, `GM_info.scriptHandler` is `GreaseMonkey`.

But in GreaseMonkey 4.x, `GM.info.scriptHandler` is `Greasemonkey`.

🤦‍♂️

**Comment by karasawa-user** [comment]
So, the issue actually lies within greasemonkey itself... Also thanks a lot for the latest update, seems it's finally resolved
