### ISSUE TITLE
Wrong mime on Safari and Tampermonkey

### ISSUE THREAD

**Issue by ivanfei-1** [ccloli/E-Hentai-Downloader#180]
I've cleared all of my cookies and enable all cookies on safari but this issue still exists.
Also I tried the 'Download original **** x **** **** MB source at the bottom of the page', and it successfully returned the original picture.
And it‘s so weird that the credit page was downloaded successfully.

[report.txt](https://github.com/ccloli/E-Hentai-Downloader/files/5714941/report.txt)

**Comment by ccloli** [comment]
Hi, sorry for the late reply. 

Are you still experience the problem? From your log it seems that the download page redirects to the login page:

```js
Request URL > "https://e-hentai.org/fullimg.php?gid=*******&page=4&key=**********"
Final URL > "https://e-hentai.org/bounce_login.php?b=ds&bt=7-*******-4-**********"
ResposeHeaders >
via:1.1 varnish (Varnish/6.0)
content-type:text/html; charset=UTF-8
cf-ray:6037f2f889777459-IAD
date:Fri, 18 Dec 2020 09:45:06 GMT
x-varnish:760835823
accept-ranges:bytes
cf-request-id:0716d62f5200007459441b3000000001
expect-ct:max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"
content-length:734
strict-transport-security:max-age=31536000; preload;
content-encoding:gzip
cf-cache-status:DYNAMIC
age:0
server:cloudflare
vary:Accept-Encoding
```

Since you can download the original image, it might be your cookie is not synced with Tampermonkey. You can let script pass your cookies by enabling `Settings` -> `Pass cookies manually when downloading images`, this should fix the problem.

If it doesn't work, maybe you can try logout then login your account, and make sure you've enabled third-party cookies for e-hentai.org if you've set disabeld third-party cookies globally.

**Comment by ivanfei-1** [comment]
This actually solved the problem. Thank you so much.
