### ISSUE TITLE
Generate zip failed

### ISSUE THREAD

**Issue by LeXuanKhanh** [ccloli/E-Hentai-Downloader#182]
It's download perfectly but in zip generating time, its always stun at 90, 95% T_T
Have enable handle large file by default
![image](https://user-images.githubusercontent.com/27200149/103454571-08601300-4d18-11eb-9c8c-b605bbb57ab7.png)

**Comment by ccloli** [comment]
I guess that's because the gallery is too large. As [file size section of README](https://github.com/ccloli/E-Hentai-Downloader#file-size-limit) noted, the maximum handle size on Chrome is at 2GB, and it seems that your gallery is 2.31 GB which is larger than 2GB, so it cannot handle such a large file (or maybe JSZip cannot handle since it's still packaging, I checked its issue just now, and some issues said they got error when r/w a large zip file). I never tried such large gallery since it'll cost all my image limits, so for stability and not wasting your image viewing limit, please try using `Pages Range` to download gallery by range, and try to limit each zip file at under 500MB.

**Comment by ccloli** [comment]
v1.33 is released just now, and it's optimized for File System (and also fixes some GC problem), so it won't wait until the zip file is completed and won't eat double RAM when generating the zip file. If you have enough RAM, you can download this gallery without any problem now. But please note that it still takes your RAM to store images, so it still needs about 2+GB RAM.

![image](https://user-images.githubusercontent.com/8115912/104107911-2e2e7e80-52fb-11eb-826b-f923e0d367ba.png)
