### ISSUE TITLE
Suddenly getting "Failed! (Network Error)" for every gallery

### ISSUE THREAD

**Issue by CSalsa** [ccloli/E-Hentai-Downloader#188]
As said in the title and the image below, the script can't download from any gallery. This happened one day ago. I tried restarting the computer, clearing the cache, and using a different residential proxy.
![image](https://user-images.githubusercontent.com/38844746/115097180-a1e1b800-9ef6-11eb-9af7-3206ff838e03.png)

**Comment by ccloli** [comment]
Test it just now and it works fine for me.

I think it may be just your network connection to e-hentai server is not good enough. If you want to check it out, please provide your browser and its version, also your userscript extension and its version.

BTW, you can press F12 and switch to Console tab, then start downloading. When it says Network Error, you should see some logs prefixed with `[EHD]`, copy all of them and paste them here, it should help to find what's up.

Also please check if you can download the image directly, please open any page of any gallery, and check if you can see the image. If it provides a link like `Download original **** x **** *.** MB source` at the bottom of the page, please click it to see whether you can download it or not.

A previous issue #187 says he cannot download any image larger than 5MB when using Chrome, and the server returns `Invalid request`, but using Firefox is fine, so maybe it's because some extensions modify the network requests. You can also try using another browser to see if that helps.

![image](https://user-images.githubusercontent.com/8115912/115110171-9c46a980-9fac-11eb-84e2-19054604c1b8.png)

**Comment by CSalsa** [comment]
![image](https://user-images.githubusercontent.com/38844746/115111252-67573a00-9f4d-11eb-8627-f58d3493444f.png)
This is what I get, I'll try on another browser.

**Comment by ccloli** [comment]
> This is what I get, I'll try on another browser.

Are you able to access any `*.hath.network` link in console? You can click it to see what it returns.

**Comment by CSalsa** [comment]
Yeah I can, it opens the direct link to the image.

**Comment by CSalsa** [comment]
It works on firefox but not chrome.

**Comment by CSalsa** [comment]
I used the same settings for both, using the force download resized image.

**Comment by ccloli** [comment]
That's a bit weird, since you can actually access to the image. But as it returns Network Error by the browser or the extension, so I'm not sure what's going on. Maybe some extensions break it?

BTW, can you also check the extension's network request? You can check it by right click the extension on Chrome, and select `Manage Extension`, and search for `background.html`, click that link, it will open a DevTools window.

Switch to `Network` tab and start downloading, and focus on the request that url contains `fullimg.php` and `*.hath.network`, and if it fails, you can check the `Status` column to see what's up. Also you can switch to `Console` tag to see full log.

![](https://user-images.githubusercontent.com/8115912/114270065-e247be80-9a3c-11eb-8af4-5775b64e1070.png)

**Comment by CSalsa** [comment]
![image](https://user-images.githubusercontent.com/38844746/115114396-19e2c900-9f5d-11eb-98d8-517f700aaa48.png)

![image](https://user-images.githubusercontent.com/38844746/115114329-b22c7e00-9f5c-11eb-864f-c83124408a2d.png)

**Comment by ccloli** [comment]
That's really weird, since the script uses the userscript extension's api `GM_xmlhttpRequest` to bypass cross-origin limit, but now Tampermonkey itself has the cross-origin issue. Will checkout what's going on, and report to Tampermonkey if I've no clue.

**Comment by ccloli** [comment]
BTW, please check the following list, it may helps to find what's up:

1. What's your Chrome's version? 
    > You can check it out by go to Chrome's settings and click `About Chrome`, or go to `chrome://settings/help` or `chrome://version/`.
2. What's your Tampermonkey version?
   > You can check it out by clicking Tampermonkey's icon in extension bar, and click `Dashboard`, it should be seen under the dashboard's logo area.
      ![image](https://user-images.githubusercontent.com/8115912/115135863-593d1280-a04e-11eb-9b58-98b54cbc4638.png)
3. Uninstall E-Hentai Download, and [install](https://github.com/ccloli/E-Hentai-Downloader/raw/master/e-hentai-downloader.user.js) it again, is that resolve the issue? If the issue is resolved, then it might be Tampermonkey has some corrupts, and you can ignore the following actions.
4. Is disabling Tampermonkey's `@connect` check helps?
    > Go to Tampermonkey's dashboard, switch to `Settings` tab, and change `General -> Config mode` to `Advanced`, and navigate to `Security -> Check @connect`, change it to `Disabled`, and click `Save` button at the bottom of `Security` section. Download again and check if it still have the issue.
    > ![image](https://user-images.githubusercontent.com/8115912/115135880-7540b400-a04e-11eb-905c-6b79339c6112.png)
    > ![image](https://user-images.githubusercontent.com/8115912/115135899-91dcec00-a04e-11eb-83c9-3153d175711c.png)
5. Are you using some extensions that modify network request? Is disabling all other extensions but left Tampermonkey enabled solve the issue?
6. If you're using the stable version of Tampermonkey (the icon is black and its version has only 2 number like `v4.12`), disable it and install [Tampermonkey BETA](https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf), then [install](https://github.com/ccloli/E-Hentai-Downloader/raw/master/e-hentai-downloader.user.js) the script, and see if that  helps.
    > Though I checked all the issues of Tampermonkey in around the last month, there's no issue about this weird cross-origin bug.

**Comment by CSalsa** [comment]
This is fixed now.

I didn't do anything except wait a few days and all functionality is back on chrome, so... thank you.
