### ISSUE TITLE
Is there a way to get it to automatically reset the Credits or GP?

### ISSUE THREAD

**Issue by arukom** [ccloli/E-Hentai-Downloader#189]
i want to download quite a lot and have loads of credit/gp but having to manually do it is rather... 

is there a way to make it automatically renew if you have enough gp?

**Comment by ccloli** [comment]
See https://e-hentai.org/home.php .

BTW since you've enough GP/credits, it's better to use E-Hentai's H@H Downloader or Archive Download feature, the GP cost of Archive Download should be similar to download original gallery with scripts then reset your viewing limits.

Also if the gallery has torrents, it's better to download them with torrents, and it's no cost.

**Comment by arukom** [comment]
ah, alright thank you for the answer!
