### ISSUE TITLE
Skip Image if error after the retries (When downloading only one image)

### ISSUE THREAD

**Issue by iShyboy** [ccloli/E-Hentai-Downloader#19]
As everyone know FF now has a option to not let the tab bring you (from the tab you're browsing) to them, when downloading a gallery with EHD with only one image per time (for some particular reason), the gallery stopped downloading at the image 13 because of a timeout error and the script brought up the option to fetch and download it again, instead of skipping it and try download the rest as before.

**Comment by ccloli** [comment]
Sorry but I can't get your point. If you mean skipped failed images and tried the others, that's how the latest version works. If you are using the legacy 1.17.4, try the latest version and set download only 1 image at the same time. But if you means always tried failed images until it succeed, I think it's useless, for others are also needed to download, it's better to download them instead of stuck in a image.

**Comment by iShyboy** [comment]
It's like this,
I was downloading a Gallery with ony 1 image per time.
Got a timeout Error and after the 3 retries a Fetch window appeared, but firefox didn't brought me to the tab in question. 
Without another image per download, the image with the error was not skipped, and got stuck.

**Comment by ccloli** [comment]
OK, the bug was confirmed, it's my fault, orz. I guest that it wouldn't be stuck in latest version.
