### ISSUE TITLE
Doesn't seem to work at all.

### ISSUE THREAD

**Issue by Tiffys** [ccloli/E-Hentai-Downloader#198]
Using Chrome Version 94.0.4606.81 (Official Build) (64-bit), Tampermonkey 4.13, and the E-Hentai Downloader script version 1.33.2.

When I visit a page, for instance ~~[this](#)~~, there is no E-Hentai Downloader box on the page. Tried reloading the page, tried a different page, tried restarting browser, tried disabling uBlock. Tampermonkey has permissions in Chrome to access all pages. Nothing. It just doesn't appear whatsoever.

**Comment by ccloli** [comment]
Hi, I've checked the gallery you provided, and it works fine for me. Please consider providing the error log, you can press `F12` and switch to `Console` tab on the gallery page, refresh the page, and copy all the logs to here.

**Comment by Tiffys** [comment]
These are the only error logs I get on that page with a refresh:

```
GET https://adserver.juicyads.com/js/jads.js net::ERR_BLOCKED_BY_CLIENT e-hentai.org/:20

GET https://adserver.juicyads.com/js/jads.js net::ERR_BLOCKED_BY_CLIENT e-hentai.org/:35 

Unchecked runtime.lastError: The message port closed before a response was received. e-hentai.org/:1
```

The latter one only appears when I move my cursor around after the page has loaded.

Under issues it has 1 issue...

```
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.

To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.

Note that for performance reasons, only the first access to one of the properties is shown.
```

If I refresh with uBlock disabled it has 4 more "issues" but no logs or errors - the ones that were there previously aren't.

```
Page layout may be unexpected due to Quirks Mode

One or more documents in this page is in Quirks Mode, which will render the affected document(s) with quirks incompatible with the current HTML and CSS specifications.

Quirks Mode exists mostly due to historical reasons. If this is not intentional, you can add or modify the DOCTYPE to be `<!DOCTYPE html>` to render the page in No Quirks Mode.
```

The added "issues" are all related to ads as far as I can tell.

**Comment by ccloli** [comment]
Please check if you've enabled the script on Tampermonkey, since I don't see any logs about the script, though the script will write some logs once it starts. You can click the Tampermonkey icon and see if the script is in the popup panel, and if it's enabled.

If it's enabled and you still get nothing, you can try switching to [another userscript extension](https://github.com/ccloli/E-Hentai-Downloader#required-environment). If you've installed other scripts on Tampermonkey and cannot switch to another one, you can install both Tampermonkey and the other extension, they should be able to run at the same time. When installing the script, disable Tampermonkey and click the install button, so that the other extension can handle the install process, and after that you can re-enable Tampermonkey.

Please let me know if it works or not.

**Comment by Tiffys** [comment]
Ah I figured out what it was!!! I had the script enabled in the Dashboard, and Tampermonkey obviously enabled in my extensions. But the hover thing for Tampermonkey (which I don't keep pinned) it said "X Enabled", clicking that and changing it to "✔Enabled" fixed it.

And you beautiful beautiful person... this also just fixed a script I've been pulling my hair out for over 2 years trying to get working that works fine in Firefox. Apparently I'm just really dumb and never figured out Tampermonkey has to be double enabled lol.
