### ISSUE TITLE
Failed (Networking Error) (Status 404)

### ISSUE THREAD

**Issue by KenTheWolf** [ccloli/E-Hentai-Downloader#217]
![DevTools - chrome-extension___gcalenpjmijncebpfijmoaglllgpjagf_background html 6_27_2022 7_48_18 PM](https://user-images.githubusercontent.com/108278029/175945812-0310bf54-68ea-47d5-8d4a-7f39a1b5b103.png)
![DevTools - chrome-extension___gcalenpjmijncebpfijmoaglllgpjagf_background html 6_27_2022 7_40_42 PM](https://user-images.githubusercontent.com/108278029/175945826-3bad3fdb-df04-4eec-88ab-42c98d13c8b0.png)
I don't know what cause this, hope everyone can help me since it always happened and download very slow ^^'

**Comment by ccloli** [comment]
![image](https://user-images.githubusercontent.com/8115912/175979215-5bf3a36e-2e4f-44ee-abde-06cb88e41e79.png)

From your screenshot, I'm pretty sure that it's because you're having a bad network, which cannot make a stable connection to E-Hentai's source image servers.

There is no way to fix it on script side, maybe you can try downloading at another time, using proxy or VPN, or changing to another ISP.

**Comment by KenTheWolf** [comment]
> ![image](https://user-images.githubusercontent.com/8115912/175979215-5bf3a36e-2e4f-44ee-abde-06cb88e41e79.png)
> 
> From your screenshot, I'm pretty sure that it's because you're having a bad network, which cannot make a stable connection to E-Hentai's source image servers.
> 
> There is no way to fix it on script side, maybe you can try downloading at another time, using proxy or VPN, or changing to another ISP.

Thanks!I have to use different VPN program for it to download normally, i had been used 1.1.1.1 cloudflare program for long but seem like it start not work well and that problem appear
