### ISSUE TITLE
Images inside zip file doesn't download at all on Safari

### ISSUE THREAD

**Issue by ymmm0** [ccloli/E-Hentai-Downloader#221]
While the interface is working fine, after the script is complete and I get a prompt to download the zip file, the file size is only 3 KB and while the names of the image files are there, the image isn't. Only the txt file managed to successfully be downloaded.

I use Safari through iPadOS using the Macaque extension.

**Comment by ccloli** [comment]
Sorry, the script only validates an old version of Tampermonkey on old macOS, and doesn't check it will work on iOS or iPadOS.

I can only guess that the mobile Safari has some weird limit, or the script manager cannot handle cross-origin ArrayBuffer, which happend on [another script manager](https://github.com/ccloli/E-Hentai-Downloader/issues/96). The script is a special case, so the script manager may need some hack to handle it.

 BTW I don't think running the script on an mobile device is a good idea, since it stores the files in the RAM, and I only checked some Android browser.

**Comment by ymmm0** [comment]
I spoke with the extension developer and they said the problem is on their end.
