### ISSUE TITLE
keep getting exceeded gp limits error

### ISSUE THREAD

**Issue by loliex** [ccloli/E-Hentai-Downloader#244]
keep getting exceeded gp limits error despite not being above the limit. Download function will only work for certain uploads and give the error for others.

**Comment by loliex** [comment]
yea looks like it has something to do with the upload dates. everything within a year is downloadable but anything older will give you an error.

**Comment by ccloli** [comment]
> Downloading original files of this gallery requires GP, and you do not have enough.

The error is returned from the server-side. Not sure what's the gap of limitations, Tenboro doesn't update E-Hentai News or post minor updates in forum.

**Comment by ccloli** [comment]
Do a little more test, seems that downloading original image from the gallery uploaded 1 year ago will requires GP.

For example, https://exhentai.org/s/af2fd4ea22/2266478-1 can be download without GP 1 minute ago, and it requires GP now.

**Comment by ccloli** [comment]
> But 2018-08-10 03:44 https://exhentai.org/g/1268244/8d9d880133/ can be downloaded No GP required

The file size of the gallery is too small, even not reaches 500KB for each file. So it doesn't have the "Download original files" link.

If you don't care about the image quality and cares about your GP costs, you can enable _Force download resized image_ in script setting, or I'd recommend download these galleries with torrent, or exchange for some GPs to download.

**Comment by ccloli** [comment]
Another way to bypass it is that if the gallery don't have image larger than 2400 width and the file size don't too large like around 2MB, you can set _Image Size Settings_ in E-Hentai Settings page and set it to 2400x. Then the site may probably deliver original images through H@H node.

Disclaimer: I enabled it and it works for a few images, but then it locked at 1280x. My account uid is under 3000000 and redeem a hath pack recently, but I cannot set back to any settings larger than 1280x. So maybe there's another limitation or threshold added recently? Use at your own risk.

**Comment by a84r7a3rga76fg** [comment]
>Site Update Log
2023-07-07
>- Galleries posted more than 1 year ago now always require GP to use the "download original image" links. As before, galleries uploaded 3-12 months ago can still use this function with the image quota outside of peak hours, while galleries uploaded less than 3 months ago can do this even during peak hours.
>(This still doesn't apply to donators, whose image limits are tied to account rather than IP address and thus cannot be "refreshed" just by switching IP)

**Comment by ccloli** [comment]
Tenboro has updated the post.

> 2023-07-07
> 
> - Galleries posted more than 1 year ago now always require GP to use the "download original image" links. As before, galleries uploaded 3-12 months ago can still use this function with the image quota outside of peak hours, while galleries uploaded less than 3 months ago can do this even during peak hours.
> 
> (This still doesn't apply to donators, whose image limits are tied to account rather than IP address and thus cannot be "refreshed" just by switching IP)

**Comment by knismaps** [comment]
> The file size of the gallery is too small, even not reaches 500KB for each file. So it doesn't have the "Download original files" link.

I found an old gallery where all the images are a little smaller than 700x1000 and smaller than 300k.  The smallest one by file size that doesn't work (and has an original image link) is 683x1000 and 281.9k.  The biggest that does work is 687x999 and 278.6k.

> Another way to bypass it is that if the gallery don't have image larger than 2400 width and the file size don't too large like around 2MB, you can set _Image Size Settings_ in E-Hentai Settings page and set it to 2400x. Then the site may probably deliver original images through H@H node.

Changing this setting doesn't seem to do anything for me with the gallery I mentioned above.  Any of the images in that gallery where the original is above 280k still get a resampled image from H@H (same resolution, but smaller file size).

**Comment by ccloli** [comment]
> Changing this setting doesn't seem to do anything for me with the gallery I mentioned above. Any of the images in that gallery where the original is above 280k still get a resampled image from H@H (same resolution, but smaller file size).

Only to say it "may probably" deliver original images. File size significantly grater than normal size will always resampled to a smaller file, but what is the "normal size" is unknown. Maybe it's related to resolution or file type? I saw an jpeg image has 2331 x 4056 and 2.33 MB, but not resized in 2400x，but another jpeg image which is 2000 x 1400 and 2.29MB is resampled to 490KB. So it's a possibility workaround, but not always working.

**Comment by knismaps** [comment]
I tried with a lot of galleries, and the site's resize option never gets a non-resampled image.  If the image has an original image link, then H@H always gives me a resampled image no matter the setting.  

> Maybe it's related to resolution or file type? I saw an jpeg image has 2331 x 4056 and 2.33 MB, but not resized in 2400x，but another jpeg image which is 2000 x 1400 and 2.29MB is resampled to 490KB. So it's a possibility workaround, but not always working.

If that first image doesn't have an original image link, can you let me know which image it is?

I do think the site decides a file size limit based on resolution and resamples anything down to under that limit.  That first image mentioned is like 9.5m total pixels versus the second's 2.5m pixels, so it's not surprising the limit for the second is much lower

**Comment by ccloli** [comment]
> If that first image doesn't have an original image link, can you let me know which image it is?

The largest file I can find in the gallery is https://e-hentai.org/s/6585d15415/2253409-13 .

```
13.jpg :: 2331 x 4056 :: 2.52 MB
```

> If the image has an original image link, then H@H always gives me a resampled image no matter the setting.

Once you see the download link, that means the original file meet the baseline that can be resampled.

**Comment by Triramama** [comment]
so we're not gonna be archiving doujinshi collections on our personal machines anymore, not for free, shucks. Panda is like the only place (I know) that stores various lossless galleries, and they decided to lock all that away, unbelievable.
While it is a reason to grieve, I'll have to ask if you know any other place you can get original h manga, assuming there's no torrent available for it. My every bookmarked site, e.g. n-hentai, hitomi, compresses and even resizes images terribly, it is unfortunate but we'll have to make do with something, just want to pick the best option available

**Comment by 1428865129** [comment]
我也遇到同样的问题了，之前可以下载就画廊，gp超额的话等一段时间仍然可以下载，现在直接用不了了

**Comment by 1428865129** [comment]
![image](https://github.com/ccloli/E-Hentai-Downloader/assets/139214582/e114f4f3-793f-4f92-a07e-ba4ef467cfe3)
这样都下载不了

**Comment by ccloli** [comment]
> so we're not gonna be archiving doujinshi collections on our personal machines anymore, not for free, shucks.

Technically not true. Though you can pass the limit if you donated around $20, once you reaches Bronze Star, your viewing limit is bind to your account instead of IP, and you can go through the GP requirement; you can still exchange for [GPs](https://ehwiki.org/wiki/Gallery_Points) to "purchase" the archive (then it's better to use the offical archive feature to download the gallery since you can redownload it in 7 days if you're having problem to download your archive), by exchange with [credits](https://ehwiki.org/wiki/Credits) or [hath](https://ehwiki.org/wiki/Hath). Ways to get them are "technically" "free" if you mean **real money**, i.e. uploading galleries, uploading torrents, hosting H@H, playing HentaiVerse, etc.

**Comment by 1428865129** [comment]
![image](https://github.com/ccloli/E-Hentai-Downloader/assets/139214582/75f74b15-2873-4dc8-a730-26ffb55cba09)

**Comment by 1428865129** [comment]
有很多旧画廊不能用洪流下载种子都失效了，只能这样抓取

**Comment by ccloli** [comment]
v1.34.6 is released, it'll give proper message when you're downloading a gallery uploaded at least 1 year ago.

> 2023-07-13
> 
> - The image limit reset function on the Home page now also always charges GP and uses the new auto-converting function.
> 
> 
> 2023-07-11
> 
> - The archiver now always charges downloads in GP.
> 
> - The archiver and full image downloads now both auto-convert Credits to GP using the "High" rate from the last 24 hours in the exchange if you have a Credit balance but insufficient GP. (In other words, you can still usually eke out a 1-2% better rate by converting manually, but doing so is no longer essential.)
> 
> - The amount of free daily credits for visiting EH was increased.

I noticed that when I downloading an old gallery, it never shows the error any more. Then I found there's an update to apply auto convert credits to GP. If you don't have GP but having credits, it'll exchange credits to GPs at the high rate of the exchange rate. Would be a nice update, so that you won't need to exchange manually, and doesn't cost at a 1:1 rate which is really high (the exchange rate now is around 1:4), though still you cannot spend your image limits to download them when downloading these ancient galleries.

***

> 我也遇到同样的问题了，之前可以下载就画廊，gp超额的话等一段时间仍然可以下载，现在直接用不了了

请查阅 [更新日志](https://e-hentai.org/news.php)，自 7 月 7 日起下载 1 年前的 gallery 都需要 GP（除非你的捐赠等级达到了 Bronze Star，此时你的限额会和你的账号而不是 IP 绑定，所以不会强制要求 GP），出现这个错误说明你没有 GP。此外，自 7 月 11 日起如果 GP 不足，会自动将 credit 转换为 GP，所以出现这个错误说明你的 credit 也不够了。

目前没有非常好的方法绕过，推荐参考官方 wiki 里提到的方式获取 GP/credit/hath 来换取 GP，并推荐花费 GP 使用官方的下载功能。

**Comment by ccloli** [comment]
Just finished my hath exchange order and purchase the "Source Nexus" hath perk, and did a small test just now.

By enabling "Source Nexus", then set "Original Images" to "Yup, I can take it", it'll deliver original image that lower than your settings through H@H network. Like if you set your Image Size Settings to 1200x, it'll deliver original image if your image resolution is lower than 1200 width, higher than that is still deliver resized image. By setting to 2400x or auto, the maximum limit will be 2400 width, any images larger than this will still resized to 2400 width.

Once it meets the resolution limit, it'll deliver original image, though maybe slower than normal resized image. And from what I can see, the viewing limit is charged at normal rate, and it doesn't cost credits (I've used up my GP so it should exchange automatically). Though I guess this may be a bug, since the new rate algorithm just applied and haven't touched this, it may changed later. 

> I do think the site decides a file size limit based on resolution and resamples anything down to under that limit.

Maybe off-topic, but I see this hilarious result, that resampled image is larger than original image.

![image](https://github.com/ccloli/E-Hentai-Downloader/assets/8115912/ce3cc0c0-01d1-47d1-a55a-f61d7dd6cb90)

**Comment by Triramama** [comment]
By "free" I of course meant "free of hassle", we're now forced either to donate or to contribute and play their stupid games. Hath? Credits? Wtf even are those? I know you've probably got a reputed account with millions of points, but that's  not the case for everyone, the majority of the userbase is idle and haven't posted so much as a single comment on the website, and they're now locked out from 90% of the content. That being said, I did manage to scrape by some gp by adding and seeding torrents and i also uploaded a gallery, which all and all brought me 150k gp in less than a day, how much images can i get with that? 
Also since you're making changes to the script can I ask you to add the gp cost calculator to be displayed at all times when downloading original images? We'll definitely be needing that now

**Comment by ccloli** [comment]
> By "free" I of course meant "free of hassle", we're now forced either to donate or to contribute and play their stupid games.

Yep, I don't like it, too. Though tbh I'm not a strong user of EH so I'm not feel that much. I could imagine why the admin made this decision, the bullshit you've heard in other place before like reducing the server load and cost, etc. If you're in an IT company, you should be familar with it in these days. At least it's not Elon Musk holding the site.

> the majority of the userbase is idle and haven't posted so much as a single comment on the website, and they're now locked out from 90% of the content

That's true but not fully agreed with it. It's true that most users don't use these fancy features, but I don't think most of these users need to download them locally. EH has the offical feature, though requires GP. The scrapy program/script, like the most awful and garbage userscript you just posted here, somewhat may hurt the site. It's already pointed out when EH increase the cost of downloading original images.

> 2019-08-22
> 
> - The "cost" for downloading the original image for a page with the "download original" link when the image limit reset function is used has been adjusted to match the cost of including it in an archive. This is because people were using scripts to download full galleries with this link instead of using the archivers, which causes a lot more strain on the servers.

> That being said, I did manage to scrape by some gp by adding and seeding torrents and i also uploaded a gallery, which all and all brought me 150k gp in less than a day, how much images can i get with that?

If you do ask for it, not for satirizing or funny, 150k GP should let you download ~4.65GB with offical archiver, or 8GB with H@H.

> Also since you're making changes to the script can I ask you to add the gp cost calculator to be displayed at all times when downloading original images? We'll definitely be needing that now

The feature is already there when it's in peak time, and the latest version also applys to galleries uploaded 1 year ago.

![image](https://github.com/ccloli/E-Hentai-Downloader/assets/8115912/a458f86c-974d-46cd-9370-43c552f0b09a)

If you cannot see it, mostly because it's not in peak hour, or you've donated to EH before, which doesn't apply the GP rule. If that matters, you can hover on the "Estimated Limits Cost" to see the GP cost.

![image](https://github.com/ccloli/E-Hentai-Downloader/assets/8115912/6b3be8a7-9652-494b-9afd-2f3f3ad14dbd)

**Comment by ccloli** [comment]
An update about Source Nexus, seems that there's still a limit at around 10MB. Once the file size is larger than that, the image showing in the page is still resized. So... there's no stable way to get older galleries without GP, even the tricky hath perk one, unless you have a time machine.

![image](https://github.com/ccloli/E-Hentai-Downloader/assets/8115912/37477069-bd6f-476f-9c2c-971fe8a1327f)

![image](https://github.com/ccloli/E-Hentai-Downloader/assets/8115912/508779fe-28c5-4696-adad-db28bc48e3e7)

Though I could understand there's a hard limit, in case the f**k someone uploaded a 45MB scan. 🤔

![image](https://github.com/ccloli/E-Hentai-Downloader/assets/8115912/8f50e797-4d59-4175-900f-c8e25325608d)

**Comment by NovaSiva** [comment]
@ccloli Is there a way to view Exh galleries on PC rather than downloading them? EHviewer seems to only work on mobile devices.

**Comment by ccloli** [comment]
> Is there a way to view Exh galleries on PC rather than downloading them?

Assuming that you have a valid account, navigate to https://exhentai.org, or http://exhentai55ld2wyap5juskbm67czulomrouspdacjamjeloj7ugjbsad.onion/ if you prefer using Tor.

**Comment by NovaSiva** [comment]
> > Is there a way to view Exh galleries on PC rather than downloading them?
> 
> Assuming that you have a valid account, navigate to https://exhentai.org and click any image to start viewing, or http://exhentai55ld2wyap5juskbm67czulomrouspdacjamjeloj7ugjbsad.onion/ if you prefer using Tor.

I apologize, but I was looking for an app that allowed for viewing of the website in a more UX friendly way. Looking through galleries on exh using exhentai.org is so incredibly painful and it loads slowly. I was looking for something more like nhentai or hitomi interface.

**Comment by ccloli** [comment]
> but I was looking for an app that allowed for viewing of the website in a more UX friendly way

Not familiar with that, though I'm using a [userscript](https://sleazyfork.org/scripts/12657-manga-loader-nsfw) to view. Maybe you can try other userscript like this [one](https://sleazyfork.org/scripts/397848-e-hentai-view-enhance) by searching in [GreaseFork](https://sleazyfork.org/scripts/by-site/exhentai.org).

Note that the image loaded from E-Hentai is through a P2P CDN network called Hentai@Home, so your connection speed and stability may vary based on the node you're connected. You may often need the "Click here if the image fails loading" link to force reload.

**Comment by Triramama** [comment]
Can I disable warning for GP costing galleries? I'm not finding the option it in the settings

**Comment by ccloli** [comment]
> Can I disable warning for GP costing galleries?

This can be done by disable warning when in peak hours.

**Comment by Ark1369** [comment]
Just saw this after all of my GP got burned randomly and EH stopped downloading, a sad day indeed.

And yeah source nexus+50k images dont help towards it.

Was curious if script could get an option to Download Original Quality automatically for galleries under 1 year, while for 1+year it uses Original Quality if you have GP to spare, else automatically fallsback to resized?

Because as it is right now, if you keep resized unchecked, u get half galleries fail to DL, while if u keep it checked -  you even get galleries you could get original for as resampled.

**Comment by Ark1369** [comment]
Yes torrents are option but part of why I use EH over others is metadata via info.txt which only comes if u download it via this script afaik

**Comment by ccloli** [comment]
> Just saw this after all of my GP got burned randomly and EH stopped downloading, a sad day indeed.

Sorry to hear that, at least it doesn't cost your credits at 1:1 rate. Though when EH posted the new rule, the script is catched up, it'll notify you when you're in peak hours or downloading galleries 1 year ago, unless:
- You've set to force download resized images, which doesn't touch the original images
- You're using onion site which doesn't have the original images feature
- You're a donator which doesn't apply the GP cost policy
- You've manually disable the warning 
- The script isn't up to date



> And yeah source nexus+50k images dont help towards it.

Source Nexus is useful for a while, but the limit to deliver original images has down from 10MiB to 3MB a few days later after I exchange it (tested by myself, doesn't see any announcement about it), so many images are over the new limit.

Maybe I'm wasting 500k credit which can be 1.5M GP, which can download ~70GB? 🤔 Though I don't visit EH a lot, so not a big deal.



> uses Original Quality if you have GP to spare, else automatically fallsback to resized?

How about try original images first, once it fails, fallback to resized? Maybe not that hard, would add it later.



> Yes torrents are option but part of why I use EH over others is metadata via info.txt which only comes if u download it via this script afaik

At least if you download with H@H it should give you some of the info, as a text file, too. But such file is not in official archiver. If the official archiver includes the file, I guess new torrents may include it, since they may uploaded from mentioned official archiver, paid by GP.

**Comment by ccloli** [comment]
A cite note about Source Nexus if you happened want it for recent GP changes.

If you're saving credits to exchange hath and redeem Source Nexus hath perk, though the price of hath in exchange market has down to ~2400c, which is a nice time to exchange for what you like, one thing you should know that there are some hidden changes about Source Nexus hath perk.

For these hidden details, I've updated it in [previous comment](https://github.com/ccloli/E-Hentai-Downloader/issues/244#issuecomment-1638632642). But if you're in hurry, in short:

- The maximum file size limit to deliver original images has been decreased from 10MiB to 3MB (2.84MiB) (1MB = 1,000KB = 1,000,000B, 1MiB = 1,024KiB = 1,048,576B)
- The cost of deliver original image has been increased from fixed 1 point to file size based 1 point per 0.1MB

So, if you're saving credits or haths just for the Source Nexus to download original images with script, I'd recommend you to give up. You should exchange something else, or use the offical archiver, which should let you download around 50 ~ 70GB depends on if you're using the zip archiver or H@H.

I remember Tenboro has said the reason why deliver original images through H@H is not a good idea (but that post is not for Source Nexus, I mentioned here is because SN is delivering images through H@H), because it takes the resources of H@H node, but don't have many hits, somehow drops the overall quality of the H@H network.

***

If you're still curious why EH made such GP limit, the moderators and Tenboro have already answered in many posts, like [this post](https://forums.e-hentai.org/index.php?showtopic=268256). The reason is the same as I mentioned before, the same as usual as you can guess, and the same as when it adds the first limit 4 years ago, the heavy server load from the original image link.

> 2. The cause of the new restriction
> 
> Much like similar restrictions added in earlier years, this new one is again caused by increased site ripping. In recent years, there seem to be more and better tools for site ripping, and more and more people starting to abuse that button at the cost of server load. These days we have rippers directly asking us here why their crawlers are not working (example [1](https://forums.e-hentai.org/index.php?showtopic=265282) and [2](https://forums.e-hentai.org/index.php?showtopic=268418)). The site offers archives, torrents and H@H as official methods for downloading galleries, and this button is not supposed to be automated for bulk download. Tenboro and others have also explained in earlier posts the more technical reasons why it is best to impose such a limit. Since restrictions were added to limit site ripping, whether they can be relaxed depends on whether rippers will show some mercy in future. They can at least slow down on newer galleries that are unaffected or only grab regular images. I understand that people want to archive stuff without any work involved, but there are too many people doing it and their pace is too aggressive.

The first time EH added the limit, is when after EX came back. I can guess people are panicking over the disappearance of EX and want to save galleries as many as possible in case it's gone again, and I did see some posts in reddit or 4chan or maybe south-plus were recommendding this script to rip the galleries at that time. I didn't add any tracking system so I don't know how many users are using the script, but I can guess there would be a peak increase at that time, which probably made much more loads to the servers before EX down. 

A big problem is that, some of the users of the script may even don't know there're offical ways to download gallery. Though it may save some people when there're torrents available, and for this case, the script will ask to use torrent first, so that you won't miss that. When I planned to made v2 (sorry it's unplanned now), I was thinking to make a big popup to say something like "You're trying to use the worst way to download galleries", "There're offical and recommended ways to download a gallery like...", but I'm too lazy, so it's not implemented.

If you're happened to be one of these, you should know that there're [offical ways to download a gallery](https://ehwiki.org/wiki/Downloading). If you're saying it requires GP/credit, you should know that there're ways to get them freely at no actual money costs. If you're blaming it's technically free but still wasting your time, though I may have the similar feeling like you, that's the rules and probably the best way for now to save cost and keep the site lives longer. If you want to help EH, consider making torrents for your downloaded archives, which should also gives you some GP/credit for latter downloads or viewing.

**Comment by Ark1369** [comment]
> > Just saw this after all of my GP got burned randomly and EH stopped downloading, a sad day indeed.
> 
> Sorry to hear that, at least it doesn't cost your credits at 1:1 rate. Though when EH posted the new rule, the script is catched up, it'll notify you when you're in peak hours or downloading galleries 1 year ago, unless:
> 
>     * You've set to force download resized images, which doesn't touch the original images
> 
>     * You're using onion site which doesn't have the original images feature
> 
>     * You're a donator which doesn't apply the GP cost policy
> 
>     * You've manually disable the warning
> 
>     * The script isn't up to date
> 
> 
> > And yeah source nexus+50k images dont help towards it.
> 
> Source Nexus is useful for a while, but the limit to deliver original images has down from 10MiB to 3MB (or say 2.86MiB in 1024) a few days later after I exchange it (tested by myself, doesn't see any announcement about it), so many images are over the new limit.
> 
> Maybe I'm wasting 500k credit which can be 1.5M GP, which can download ~70GB? 🤔 Though I don't visit EH a lot, so not a big deal.
> 
> > uses Original Quality if you have GP to spare, else automatically fallsback to resized?
> 
> How about try original images first, once it fails, fallback to resized? Maybe not that hard, would add it later. Though I'm still having ~600k credit, with the auto GP exchange function, I don't think I will reach that error message, maybe I'll just yolo it.
> 
> > Yes torrents are option but part of why I use EH over others is metadata via info.txt which only comes if u download it via this script afaik
> 
> At least if you download with H@H it should give you some of the info, as a text file, too. But such file is not in official archiver. If the official archiver includes the file, I guess new torrents may include it, since they may uploaded from mentioned official archiver, paid by GP.

Yea I missed this update,  unfortunately (Was on last version) so while all other options and reminders were there. Didnt know about 1 year GP rule (Ended up using all credits too :p)

>How about try original images first, once it fails, fallback to resized? Maybe not that hard, would add it later. Though I'm still having ~600k credit, with the auto GP exchange function, I don't think I will reach that error message, maybe I'll just yolo it.

This would work yea, and damn thats a lot of credits. Down to 2k credit and 4kGP (Doing some torrents of stuff I have now to get some leeway but is slow process)

Can't use H@H as unfortunately Im on C-Nas network so IP is not Static.

Had Source nexus for long time now so sad to see its functionality go lower.

**Comment by ccloli** [comment]
> This would work yea, and damn thats a lot of credits. Down to 2k credit and 4kGP (Doing some torrents of stuff I have now to get some leeway but is slow process)

@Ark1369 Sorry about that, if you're a daily user and usually downloads with script, that would cost you a lot. If you don't mind telling your E-Hentai username, I'd like to send you 100k credits through HentaiVerse MoogleMail as a present for you.

**Comment by Ark1369** [comment]
Wow, I don't know what to say except really thank you very much. But please only do so if its not a burden to your own usage.
Username would be HentaiNingen13.
Thank you very much once again @ccloli

**Comment by ccloli** [comment]
@Ark1369 A mail titled "100k" has been sent to your given account, check it in HV and if anything goes wrong, don't hesitate to reach me.

**Comment by Ark1369** [comment]
@ccloli thank you very much!
![image](https://github.com/ccloli/E-Hentai-Downloader/assets/123398211/78d175e9-f0a9-4050-87e0-f84aac9e1a2c)

**Comment by Ark1369** [comment]
Might be an overall useless feature/rant, but how about allowing the script to download just the info.txt from the site? It would allow the user to have best of both worlds where Torrents exist - Files without expending GP and metadata/gallery info via script.

(But ofc it could be very niche based used, I cant really comment on how many people have use for metadata in info.txt saved)

**Comment by Franck-Nein** [comment]
I have 183 Hath, I was saving for the 250 Hath "All Thumbs" perk, But now I'm thinking of spending most of my 343 kGP to get the "Source Nexus" perk, would you recommend me to do it, or should I not bother?
My Hentai@Home Client should make about 9 Hath by the time they increase the prices if I'm lucky, so I will have to spend between 100 kGP and 200 kGP to get it, I have been saving GP for years, mostly by creating and seeding torrents, so I'm hesitant to spend them.

**Comment by ccloli** [comment]
> I have 183 Hath, I was saving for the 250 Hath "All Thumbs" perk, But now I'm thinking of spending most of my 343 kGP to get the "Source Nexus" perk, would you recommend me to do it, or should I not bother?

As for now, if you can switch to 2400x (it may requires uid < 3000000), then for now I'm not recommending it. Since the file limit has down to 3MB, and most images from scans are larger than that, so most of the images are resized, enable  original images are mostly like switching to 2400x. Unless maybe at some time it reverts to original behavior, which can deliver 10MiB, then I'd recommend it, but that may requires you to increase your image limits, too, since it's now counted by file size.

But it may not the best time to exchange hath compare to a few days ago, before it announced that the price of some gallery-related hath perk will significantly increased. If you come earlier, you can exchange hath at 2400c, but after a few rounds of bunch buyer (I've seen twice that a buyer bought all the hath below some point, like the screenshot I posted all the < 3500c are bought, and yesterday another one bought all hathes under 4500c), it's now increased to 3800c avg. Since the top seller are also the top buyer, they're controlling the prices (recent transaction shows the low price seller and the high buyer are the same one, they're earning the big hundreds credit gap from the chaos), unless someone buy or sell many hath again (which is very likely), the price would go high in the near future. Sadly I didn't exchange early, seems that in a way I lost around 100 hathes.

Though it's not a good time to exchange hath, but if you have some hath perk want to buy, then I still recommend you to redeem them now, some of them especially gallery related will go much higher, higher than the hath exchange increases. If you're still not sure what to buy, buy the most wanted first, then consider buy the one that you may want but requires more hath to unlock in the future.

> QUOTE(Tenboro @ Aug 4 2023, 16:29) *
> 
> These perks will change:
> 
> Ads-Be-Gone: 20 -> 200
> Source Nexus: 200 -> 1000
> More Thumbs: 50-100-250 -> 200-400-800
> More Pages: 20-50-100 -> 200-500-1000
> More Favorite Notes: 100-250 -> 500-1000
> Paging Enlargement: 100-500 -> 500-1000
> Postage Paid: 10 -> 100
> Vigorous Vitality: 250 -> 1000
> Effluent Ether: 500 -> 1000
> Resplendent Regeneration: 500 -> 2000
> Extra Strength Formula: 500 -> 2000
> That's Good Eatin': 1000 -> 2000
> Crystarium: 250-500-1000-2000-4000 -> 1000-3000-5000-7000-10000
> Innate Arcana: 50-100-250-500-1000 -> 500-1000-1500-2000-2500 (note that this perk was recently changed, all five autocast slots are now always available and the perk only affects the upkeep discount)
> 
> If a perk isn't mentioned in the list above (like MPV), the cost will remain the same.

**Comment by Franck-Nein** [comment]
I decided to spend some GP to get the Source Nexus perk, and wait for 2 years for my Hentai@Home Client to produce enough to get the last More Thumbs perk.
Thanks for explaining everything, I was probably going to panic and spend all my GP trying to buy the cheap stuff without your help.

**Comment by DestinoAzell** [comment]
I need help! after downloading an image gallery... 1st I got an red writting says MME something on the download file name.
Then soon after I can't log-in my e-hentai account.
The it took me to white page.
It says BROWSER(YOU) WORKING -> CLOUDFLARE WORKING -> HOST (forum.e-hentai org) ERROR.
Does this mean I got banned?

**Comment by deusvlad20** [comment]
GP system is ridiculous to begin with, they that poor they have to coerce people into buying into something to get more GP? What a cuck design. I bet the owner is a child that wants to be king to control things online because he can't control shit in real life.
