### ISSUE TITLE
[Request] Close Tab After Successful Download

### ISSUE THREAD

**Issue by iShyboy** [ccloli/E-Hentai-Downloader#25]
There's a way to put a checkbox in the settings to let  the script close the tab if the download was successful?
I, and many people (I think), probably download many things and start doing another thing during the downloads, it'll be cool if there's a option to close the tab after de download completed.

**Comment by ccloli** [comment]
If you mean close current page after completed, it's a bit hard because it's not opened by JavaScript but a human. BTW, in Google Chrome you may meet [_File not exist_](https://github.com/ccloli/E-Hentai-Downloader/wiki/Can't-make-Zip-file-successfully#chrome) if there is no enough free Blob Storage, and we can't detect it because Chrome won't throw an error like Firefox. Thought auto-close is a useful feature, there are still some uncontrollable problems, so it won't be added.
