### ISSUE TITLE
Setting "Pin download actions box at the top of the page" behaves opposite of what you set it to.

### ISSUE THREAD

**Issue by Liniert** [ccloli/E-Hentai-Downloader#263]
Hello, I am using Tampermonkey 4.11 with E-Hentai Downloader v1.35 and I just noticed that the download actions box suddenly moves when scrolling in a gallery.

It didn't do that before since I have the setting "Pin download actions box at the top of the page" activated.
Now I have to uncheck that setting in order to keep the download actions box in place above the gallery.

[x] "Pin download actions box at the top of the page" => box moves when scrolling down.
[  ] "Pin download actions box at the top of the page" => box stays in place when scrolling down.

Did something change in the last week or so that makes it behave that way?

**Comment by ccloli** [comment]
The setting was added in v1.35, though it's not intended, it should be added when #246 is done. It's released early than that is to release a hotfix to site update.

The behavior is intended, when it's enabled, it'll be pinned (or say sticked) at the top of the viewport, so that you can control pages range easier.

So in fact, the feature is not existed before v1.35, and it's enabled by default in new version. But the feature will be reverted in the next version until #246 is added.

**Comment by Liniert** [comment]
Ah, I see, that makes sense. Thank you for the response.
The wording and the sudden change in the behavior confused me a little bit, so I thought pinning was supposed to keep it in the place above the gallery where it usually was. If others should find this confusing aswell, maybe you could add something like "Pin download actions box at the top of the viewport when scrolling" to the description of that option.

I think this topic can be marked as "closed" then.

**Comment by ccloli** [comment]
v1.35.1 is out, the feature is removed for now.
