### ISSUE TITLE
Don't work with Safari

### ISSUE THREAD

**Issue by lamons** [ccloli/E-Hentai-Downloader#27]
The download finished but the zip is not downloaded, a blank page popped out but nothing happened when clicked the "Not download?" button. 

Version: 1.19.9
Safari: Version 9.1 (11601.5.17.1)

**Comment by ccloli** [comment]
I'm sorry that I don't have a Mac OS device, so I can't test it right now.

How about pressing ⌘ + S in the new page? As FileSaver.js says, Safari will open it instead of save it, so you need to press ⌘+S to save the file.

**Comment by lamons** [comment]
Not working... that page is unsaveable. 

I don't programming but if you need to test anything, I'm willing to help.

**Comment by ccloli** [comment]
Hmm...I'm not sure how to test it, anyway thanks for your help. 

I'm downloading Mac OS X now, during this time you can try other tools, like the forked node-webkit version: https://github.com/8qwe24657913/E-Hentai-Downloader-NW.js

**Comment by ccloli** [comment]
From my testing, Safari (8.0, 10600.1.25, sorry I can't test with latest version) can't open and decode content of a `blob:` URL. Here is an issue on FileSaver.js: eligrey/FileSaver.js#12, and seems that it's a long term problem on Safari, I'll remove Safari from the supports list. I'm sorry that I can't fix it. :disappointed:

**Comment by lamons** [comment]
Oh, that's sad... Thank you anyway.

On Thu, Apr 21, 2016 at 1:06 pm, 864907600cc <notifications@github.com> wrote:
From my testing, Safari (8.0, 10600.1.25, sorry I can't test with latest version) can't open and decode content of a blob: URL. Here is an issue on FileSaver.js: eligrey/FileSaver.js#12 [https://github.com/eligrey/FileSaver.js/issues/12] , and seems that it's a long term problem on Safari, I'll remove Safari from the supports list. I'm sorry that I can't fix it.

**Comment by ccloli** [comment]
Hi, after a year, this bug has finally been fixed. :-)

In early of April, Safari 10.1 was released, which [finally supports HTML5 `download` attribute](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html), so that you can finally download the file now. Sorry for late reply because a bug on Tampermonkey makes the script cannot pack the images, now it has been fixed in latest version 1.26. What you need to do is to upgrade your macOS 10.12.4, then update your Safari to 10.1.
