### ISSUE TITLE
bug report 1.35.2

### ISSUE THREAD

**Issue by etybgm** [ccloli/E-Hentai-Downloader#275]
1.35.2
Show inputs to recheck file name and folder name before downloading:
(C100) [焼肉定食 (ハラミ)] もしも担当アイドル北沢志保と付き合ったら ~後編~ (アイドルマスター ミリオンライブ!)
Completed:
(C100) [焼肉定食 (ハラミ)] もしも担当アイドル北沢志保と付き合ったら _後編_ (アイドルマスター ミリオンライブ!).zip

~->_

**Comment by ccloli** [comment]
Checked the source code just now:

```js
	var replaceList = {
		':': '：',
		'"': '＂',
		'*': '＊',
		'?': '？',
		'|': '｜',
		'<': '＜',
		'>': '＞',
		'/': '／',
		'\\': '＼',
		'\n': '-'
	};
```

Seems that `~` is not in the list, even in the first version which introduced the the feature.

![image](https://github.com/user-attachments/assets/c54933e0-9cba-4351-829e-4d1c40517386)

Besides, the script replace these symbols into `-` instead of `_`. So I'm aware the filename is changed by the browser itself, not on the script side.

**Comment by etybgm** [comment]
Can I replace the symbol ~ with the full-width ～ in script side?
