### ISSUE TITLE
`Failed! (Wrong MIME)` error

### ISSUE THREAD

**Issue by AlttiRi** [ccloli/E-Hentai-Downloader#290]
I faced the `Failed! (Wrong MIME)` error the first time.
The script _constantly_ tries to download a URL that returns `"Invalid request"` text.

_How to fix it:_

~The script should refetch the image gallery page and take the new updated image URL.~

The script should perform the request with **disabled caching.**

The problem reason is that `/fullimg/` redirect was cached:
![image](https://github.com/ccloli/E-Hentai-Downloader/assets/16310547/c84179f4-23eb-40e2-98ed-3687982a2b59)

After "Disable cache":
![image](https://github.com/ccloli/E-Hentai-Downloader/assets/16310547/ca8d4016-72e7-499b-a1c9-e4c0e89a5221)

the problem was disappeared.

So, I think, you just need to add the `cache-control: no-cache`, `pragma: no-cache` headers for `/fullimg/` request when `Failed! (Wrong MIME)` error with `Invalid request` text payload is returned.

https://stackoverflow.com/q/10314174/

**Comment by ccloli** [comment]
Thanks for the tip, though I remember that the userscript extension itself will disable cache by default, and the script will use the final redirect url of fullimg redirect link to save image limits, so in theory the fullimg link will request only once, which shouldn't have broken cache.

I guess it's because of some changes since Chrome extension manifest v3, and I've seen a few bugs that never happens before.

**Comment by AlttiRi** [comment]
You can check with DevTools, that there is no cache disabling headers in the requests neither from the web page, or from the background script.

Here is the `fetchURL` is cached:
![Screenshot](https://github.com/ccloli/E-Hentai-Downloader/assets/16310547/aa5165a2-c136-46ba-beca-5b5304b048ec)

It happens, for example, when the certain `hath.network` server "returns" `ERR_CONNECTION_RESET`.

I think the http cache algorithm works everywhere the same way.

Also, it happened on a relatively old Chrome that does not support MV3.
