### ISSUE TITLE
[Request] Add a pause/resume button

### ISSUE THREAD

**Issue by nodevicefound** [ccloli/E-Hentai-Downloader#30]
Can you please add a pause/resume button on the download status mini screen?

Sometimes if the gallery size is big, after more than 30% or 50% have been downloaded, I remember something more important. So I have to close the tab and download again later. But my image limits are consumed due to the previous partial downloading. So, a pause/resume button would be appreciated.

**Comment by ccloli** [comment]
I understand, but here is a problem that has been mentioned in https://github.com/ccloli/E-Hentai-Downloader/issues/5#issuecomment-136361378 : we can't get downloaded part if download is not finished. So if we pause (or say abort, in fact) all the download requests, the downloading images will have to re-download. 

However, the images that have been downloaded will be kept in RAM, so they won't have to download again, just hold some RAM space. If you think it's acceptable, I'll try to work it out in next version, it seems that it's not hard.

**Comment by version365** [comment]
Yes of course I understand that those downloaded images will hold some RAM space until the whole gallery gets downloaded. This should be acceptable for everyone. I will look forward to the next version. Thanks a lot for your time.

**Comment by nodevicefound** [comment]
Yes of course I understand that those downloaded images will hold some RAM space until the whole gallery gets downloaded. This should be acceptable for everyone. I will look forward to the next version. Thanks a lot for your time.

**Comment by ccloli** [comment]
Sorry for keep waiting too long, in these months here are some serious bugs (or even script handler) so that I can't work on it. Now this feature is added in 1.22, after updated, you'll see the pause button when downloading. 

It won't abort downloading images by default, you can let them aborted by changing its behavior on _Settings > Advanced > Force drop downloading images data when pausing download_.

By the way, as Tampermonkey/tampermonkey#298 is not fixed right now, you may meet some problems on Tampermonkey. This feature probably **can't** work correctly on Tampermonkey (mostly for Chrome user), so please try GreaseMonkey (Firefox only) if needed.

**Comment by iShyboy** [comment]
Worked fine in my FF, but could you change where the button is? Like in the 'on hover' line that appear or in the infobar at the top, the one with total|downloads|fails

**Comment by ccloli** [comment]
@iShyboy I'm not sure it will be useful, with keeping showing in bottom, users can know this feature and current status (pausing or not). If showing when mouse hover, it would also cover the progress table so that you can't abort some connections. And if showing on top, does it take too much place?
