### ISSUE TITLE
source nexus perk [Question]

### ISSUE THREAD

**Issue by Ashkar666** [ccloli/E-Hentai-Downloader#305]
I just wanted to find out, if you have the source nexus perk, does the "Force download resized image" setting matter anymore?

How does the perk effect the function of the downloader, I tried downloaded the same gallery (an archived gallery from several years ago with very high resolution images) with and without the setting, and the only difference I noticed in the file downloaded was the .cbz file itself was smaller with the setting on, but the images inside seemed to be the same in both downloads.

Other than that, what I noticed is with the force download setting it didn't cost me any GP, but with the setting off it did.

Also, does the estimated cost take the perk into account or does that matter?

**Comment by ccloli** [comment]
> I just wanted to find out, if you have the source nexus perk, does the "Force download resized image" setting matter anymore?

Source Nexus doesn't guarantee that it will always return original files. Currently the rule is:

> - When browsing with "Prefer original images" enabled, the cutoff for when resampled images will be used is now 10 MiB for galleries posted in the last year, and 4 MiB for older galleries.

When the file exceeds such limit, you'll get 2400x resampled image. For those files downloading original image will send another new request which costs your image limits or GPs depends on how old the gallery is and the cost is based on the file size.

For the detail rules, have a look at https://github.com/ccloli/E-Hentai-Downloader/wiki/E%E2%88%92Hentai-Image-Viewing-Limits , which is mostly accurate.



> Also, does the estimated cost take the perk into account or does that matter?

Yes but not accurate. For now the Source Nexus counts the cost by total gallery size instead of individual files. So if the gallery is new and no GP rules applies, then it's accurate since it only costs your image limits. But beyond that, some of them will use limits (<= 10MiB/4MiB) and the others uses GPs, then there's the gap. For now the script will show the summary of GPs cost and limits cost, which is significantly larger than the actual cost.

**Comment by Ashkar666** [comment]
Ok, thank you, after looking into it more, I see what it means about the 4MB limit, that explains why I thought the downloads were the same even though they were different sizes, some of them downloaded the full original, and some were the +4MB resamples.
