### ISSUE TITLE
When downloading large gallery =>600MB

### ISSUE THREAD

**Issue by YukiSakuma** [ccloli/E-Hentai-Downloader#32]
When the downloader finishes downloading and asks me where to save the zip file then I save it. It downloads the zip file to my computer but for some reason the archive is "no file size" if I remember correctly. I am pretty sure my RAM can handle 600MB and up gallery sizes I am using Chrome browser

**Comment by ccloli** [comment]
Are you using Google Chrome? Google Chrome can only handle 500 MB file without using File System, so try enabling it in Settings -> Advance. If you are using Firefox or already enabled File System, it would probably related to #31 , but I'm not sure. If you have any updates, please let me know.

BTW, Have you ever tried clicking the button "Not download? Click here to retry"? And can you show me your browser version, script handler (GreaseMonkey, Tampermonkey or others?), RAM size here?

**Comment by YukiSakuma** [comment]
I tried "Not download? Click here to retry" many times before and still no luck 
Using Cent browser Version 1.8.9.28 (64-bit) (portable) but it happened also on Slimjet and the original Chrome browser. I can't find any "Advance" in the Settings and "File System". Using Tapermonkey
RAM:32GB
EHD?

**Comment by ccloli** [comment]
Hmmm......Is this bug happened on all galleries? If just only this one have the problem, have you ever tried this feature (File System) on screenshot? It's the only way to handle 500+MB file on Chrome. Or how about using Pages Range to download them into some parts?
![Uploading 20160517_184241png.jpg…](http://r5.loli.io/nqAJJr.jpg)

If you have already enabled it, it would probably be a bug, please paste the gallery URL here if acceptable. When it happens next time, press F12 and switch to "Console" tab, then copy all the logs and paste them here. 

Anyway, sorry for wasting your image viewing limits, if you are bored about it, try torrents or other tools.

(**EHD**: Sorry I mean E-Hentai Downloader)

**Comment by YukiSakuma** [comment]
thanks it's. Would try downloading it with file system enabled it might take a while though as I have crappy internet :+1:

**Comment by dodying** [comment]
@ccloli 等等，CC大大用的什么手机浏览器啊，支持UserJs？

**Comment by YukiSakuma** [comment]
I tried to download this with file system enabled

http://exhentai.org/g/561901/4c6ccd0e9a/
and it no luck again :(
it says "Failed - No file" this is the one I am talking about
Where is this "log" located in the console?

**Comment by ccloli** [comment]
@YukiSakuma My network is a bit mess, so I have to build a localhost to simulate. Luckily the bug is confirmed, I'll working on it. If I have anything updated, I'll put them there.

@dodying UC 浏览器国际版（搭配 Tampermonkey for UC）。另外海豚浏览器国际版也支持（搭配 Tampermonkey for Dolphin），不过肯定都不能跑这个脚本。Firefox 移动版好像也有扩展能支持脚本的样子。

(He just asked me what's the browser I'm using on my phone that can run user scripts. I'm using UC Browser (with Tampermonkey for UC) and Dolphin (with Tampermonkey for Dolphin). However both of them can't run this script. Seems that Firefox also have an extension to support it.)

**Comment by ccloli** [comment]
It's sure that the problem is related to not using File System, because the size of Blob Storage on Chrome is 500 MB. And here is a bug that after upgrading to JSZip v3, File System is not working correctly, so thought you have enabled File System, the Zip file is not stored into it :disappointed: 

Now this bug has been fixed, have a test with latest version if possible, and if the bug is still exist, please report here. ( I'm sorry that the download speed to E-Hentai original server is too slow here, so I have only tested it with localhost, and a 600+MB file is downloaded successfully and Zip file test is OK.

**Comment by YukiSakuma** [comment]
How do I determine I just updated but to be sure I need to see the version installed?

**Comment by ccloli** [comment]
Thanks for your testing. Anyway it's really late in my time zone, I'm sorry for can't waiting for you. I'll see your test result in the morning, sorry for that.

BTW, it's better to download a large gallery with torrents (you can download it from the right side of gallery page if possible), at least you can pause and resume it at any time. Have a try next time ;-)

**Comment by YukiSakuma** [comment]
well we live in the same time zone region I'm just nocturnal ;)
I downloaded the same link and it was successful. Thanks for fixing it
In the near future I might try downloading 1GB
