### ISSUE TITLE
Why check response sizes instead of the status code?

### ISSUE THREAD

**Issue by knismaps** [ccloli/E-Hentai-Downloader#39]
I was looking through the code and see a few checks like this one:

https://github.com/ccloli/E-Hentai-Downloader/blob/master/src/main.js#L940

Why are you checking the response size instead of res.status?  The code for things like the image limit probably never change from 509, but the response size can probably change just because they feel like changing the response slightly.

**Comment by ccloli** [comment]
Hi, sorry for replying so late. It's really a tough work to review my code, happy to see you that you are not in mad :-)

In fact, this parts was added in some earlier commits, I thought that should be this time of the last year (sorry that most of the commits in last year are in Chinese). At that time, someone said that he reached some problems that most of the images are not correct. As I could only get the wrong file and didn't reproduce them for myself, I just simply check them with the length of contents. So as you know, all the wrong-file-detects are based on file size. 

Sometimes it based on `res.status`, however, both the `res.status` of _403 Access Denied_ image and _An error occurred (403)._ text are `403`. To declare the differences of them, I tested the byte length first, then `res.status`.

Anyway, this parts should be a hotfix at that time, but now it becomes a mess, maybe I should use a better way to check them.

If you have any questions or ideas, it's happy to let me know. :-P

**Comment by knismaps** [comment]
I think, but am not sure, that while I was downloading a gallery I hit my image limit but the userscript didn't abort.  I came back to see many files listed as failed in red and my image limit was very, very high.  I started out at like 4k out of 5k and ended up at 18k.  Maybe it failed to properly detect the 509 and kept trying (and retrying), which would keep adding to my limit.

If there's only one kind of response for the status code, it's definitely better to check the code.  In the case of 403, I think it's better to look at the response data (or maybe MIME type).

**Comment by ccloli** [comment]
Seems that [here](https://github.com/ccloli/E-Hentai-Downloader/issues/35) is a poor child that likes you. Maybe both of you are having the same problem.

Your idea would probably works, if I have free time I'll tried on it and update here.

CC @YukiSakuma

**Comment by ccloli** [comment]
Finally reached the limits _(:3

Seems that `res.status` is not working because it's `200 OK`.
![qq 20160723014157](https://cloud.githubusercontent.com/assets/8115912/17065947/2e932afa-5077-11e6-8b6e-d83748c60582.png)

But it can be detected from URL simply.
![qq 20160723014104](https://cloud.githubusercontent.com/assets/8115912/17065995/7b7ff320-5077-11e6-9cff-e3e7b7fe7256.png)

However I checked the file size of 509 image, it's still `28658`, so the possible reason you mentioned shouldn't be happened at this time, it should be a logical bug on how to pause all the dowload threads.

It's a bit late in my timezone, I'll check it tomorrow.

**Comment by YukiSakuma** [comment]
I don't know if the latest version of the script causes this but whenever I try to download EHT torrent it crashes my browser (Cent browser)

**Comment by knismaps** [comment]
I use Firefox nightly with GM on Windows, I have had a tab crash just once (e10s).  Another time the tab was just blank white, so probably also something involving e10s.

**Comment by ccloli** [comment]
I'm sorry I still can't reproduce your problem, I tried to increase my viewing limit to 5K, thought it had some bugs like can't recover download progress, it still paused successfully, and my image limit didn't increase anymore. 

Can you show me your E-Hentai Downloader Settings? You can screenshot them or open a gallery, press F12 and switch to Console, then copy all the logs that started with [EHD].

**Comment by knismaps** [comment]
I think in the past it's worked correctly.  I haven't tried reproducing it after opening this issue.

    [EHD] E-Hentai Downloader is running.
    [EHD] Bugs Report > "https://github.com/ccloli/E-Hentai-Downloader/issues | https://greasyfork.org/scripts/10379-e-hentai-downloader/feedback"
    [EHD] To report a bug, showing all the "[EHD]" logs is wonderful. =w=
    [EHD] UserAgent > Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0
    [EHD] Script Handler > GreaseMonkey
    [EHD] Script Handler Version > 3.8
    [EHD] E-Hentai Downloader Version > 1.21.10
    [EHD] E-Hentai Downloader Setting > {"thread-count":2,"speed-detect":true,"number-images":true,"number-separator":"_","number-real-index":true,"number-auto-retry":true,"dir-name":"/","ignore-torrent":true,"status-in-title":"never","hide-image-limits":false,"file-descriptor":false,"force-resized":false,"never-new-url":false,"never-send-nl":false,"store-in-fs":false,"save-info":"file","image-limits-both":false}
    [EHD] Current URL > "..."
    [EHD] Is Logged In > true`

**Comment by YukiSakuma** [comment]
> bugs like can't recover download progress/some images that fail to download never recovers ,
I sometimes get this too but don't know what causes it
I tried firefox and now able to download EH torrents maybe it's something with my chromium based browser that causes to crash it.

**Comment by ccloli** [comment]
Bug confirmed just now, it happens when an image has original size link. That link doesn't point to 509.gif, but show the text: `You have exceeded your image viewing limits. Note that you can reset these limits by going here.`. So in E-Hentai Download you may see they looks like `Wrong MIME-Type` because it response status is `200 OK`, but response type is `text/html`. As before, this mostly happened when you are using a proxy client like GAppProxy and Shadowsocks, so E-Hentai Downloader will retry them, which leads to high image limits. Besides, if you enabled _Retry automatically when images download failed_ (lol, you really enabled it), you can't get any notification, and script will keep fetching them.
![qq 20160725231903](https://cloud.githubusercontent.com/assets/8115912/17106604/84ec9a14-52be-11e6-90f7-2e8178102dc2.png)

**Comment by ccloli** [comment]
I tried to fixed it in 1.21.11 and 1.22, and from my test it should work fine now. If you have any questions, please let me know :stuck_out_tongue_closed_eyes:

**Comment by knismaps** [comment]
Thanks for looking into it.  I'll reopen if I find it's not fixed.

**Comment by knismaps** [comment]
I just tested it and it did correctly stop the download.
