### ISSUE TITLE
Script not working on exhentai

### ISSUE THREAD

**Issue by HackPC** [ccloli/E-Hentai-Downloader#41]
on exhentai script not working but g.e-hentai is work 
how to fix it

**Comment by iShyboy** [comment]
UP!!

**Comment by HackPC** [comment]
Ok i fixed change http:// to https://

 @match        https://exhentai.org/g/*
// @match        https://g.e-hentai.org/g/*
// @match        https://r.e-hentai.org/g/*
// @include      https://exhentai.org/g/*
// @include      https://g.e-hentai.org/g/*
// @include      https://r.e-hentai.org/g/*

that work again

**Comment by ccloli** [comment]
I tested the latest version, it works fine. From your last comment, it seems that you are using HTTPS? WOW, that's amazing, I even don't know E-Hentai now supports HTTPS.

**Comment by iShyboy** [comment]
Maybe conflit with something like HTTPS everywhere (addon)

**Comment by HackPC** [comment]
It seems exhentai only using HTTPS

**Comment by ccloli** [comment]
However it's interesting, I remembered that on E-Hentai Forums, a manager said that as Hentai@Home is using HTTP (means mixed content, because the host name is IP so that it's also hard to create their own SSL certificate), E-Hentai won't use HTTPS, because it's probably useless. 
It seems that SSL is just enabled in these days, for the certificate is started on 2016/07/18.

**Comment by ccloli** [comment]
Fixed in 1.22.1.
