### ISSUE TITLE
Remaining image counter is wrong (FFox 48.0.1)

### ISSUE THREAD

**Issue by typhoon71** [ccloli/E-Hentai-Downloader#45]
With FFox 48.0.1 remaining image counter is wrong: it seems to be showing the "used" image count instead.
Basically it will starts from zero and go up while you  download images.

**Comment by ccloli** [comment]
I'm not sure sure what you mean, sorry for my bad English. :disappointed: 

From my side, each number shows correctly, so probably you got it wrong. Here are the meaning of each number, hope this can help you.

_Total_: The count of images that __need__ to download.
_Downloading_: The count of images that are __active__ and downloading now (not remaining).
_Succeed_: The count of images that has been __downloaded__.
_Failed_: The count of images that download __failed__.

**Comment by typhoon71** [comment]
Sorry, I mispoke. I was referring to the "Image Limits". 
It usually shows 5000/5000; the more images one downloads the more the counter goes down, till it reachs 0/5000, where you can't get any more image (the script will stop).
Then waitinf some time, that counter will starts to go up again till 5000/5000.
Right now it's decreasing instead.
Also, when I started getting stuff this morning it was 0/5000 (instead of 5000/5000), so I shouldn't have been able to download any image at all.

**Comment by ccloli** [comment]
Image limits is referring to http://g.e-hentai.org/home.php , so it should be __used__ image limits, not __remaining__ image limits. In order to prevent being confused, the script will output the number which showing on that page, without any process. So actually it should start at 0 and increase when you are viewing pages or downloading, not counting down. And when the number reaches the limit (normally it's 5000), you can't download any more. So showing the used image limits is correct.

**Comment by typhoon71** [comment]
Funny, I never checked http://g.e-hentai.org/home.php, and just checked the addon's counter.
So it was behaving wrongly before and now it's behaving correctly? Go figure.
