### ISSUE TITLE
Uploader Comment as zip comment

### ISSUE THREAD

**Issue by iShyboy** [ccloli/E-Hentai-Downloader#46]
Can we have the uploader comment as zip comment? Every now and then when I'm reading something that I downloaded some time ago I took note that it's a multi-series or something the like and it's a bother to look into the gallery again to search in the uploader comment for the order or the like. Well, can we have that as a zip comment?

**Comment by ccloli** [comment]
Hi, in fact, if the uploader commented the gallery when it published, E-Hentai Downloader will automaticly added them to `info.txt` since 1.12 released.
![info.txt](https://cloud.githubusercontent.com/assets/8115912/18232420/c27424d4-7301-11e6-80e3-4e047d85e9e1.png)

Besides, you can change to store it as zip file comment, just simply change it at _Settings ->Advanced -> Record and save gallery info as [Zip Comment]_. But note that most of zip-compress program (like WinRAR, WinZip, 7-Zip) doesn't support UTF-8 comment, so that letters which isn't ASCII letter will be messy. From my test, only BandiZip supports multiple encode comment.
![Screenshot of WinZip and BandiZip](https://cloud.githubusercontent.com/assets/8115912/18232509/875901ce-7303-11e6-9fd4-edbe85f36521.png)

**Comment by iShyboy** [comment]
I'm a lover of bandisoft since years so I'm fine with bandizip for some time already (I use honeyview to read too), but can't we shrink it up of the pages and the  the rest? Just the uploader comment and the gallery link (since someone most likely will put the information if it's missing).

**Comment by ccloli** [comment]
I think probably someone that needs `info.txt` also want some more details. Probably the most useless part is the link and file name of each page, I think with this part, users can quickly get the image URL if they find an image is broken, or they can't find the correct order of all the files. And it doesn't take too much place (~10KB), so probably I would rather keep them like before.

**Comment by iShyboy** [comment]
It's not for the size, just the visual, I can live with this. I don't even use `info.txt`, just zip comment.

**Comment by iShyboy** [comment]
Workout idea:
Record and save gallery info as  
>
- None
- Zip Comment
- Info.txt 

Save only
>
- Full Info
- Uploader Comment
- Pages info

_if none just gray out the second dropdown_

This way we would use the same line and wont mess anything in the settings page.

**Comment by ccloli** [comment]
Hi, in latest release (1.24) you can use checkbox to select what you want. For example, if you just want uploader comment, you can only select _Uploader Comment_ like this.
![qq 20161101110159](https://cloud.githubusercontent.com/assets/8115912/19878370/a626f47a-a022-11e6-8228-d02884de8868.png)

If you have any question or idea, feel free to let me know 😛
