### ISSUE TITLE
"An error has occurred. (403)" files being downloaded by the script on Firefox.

### ISSUE THREAD

**Issue by Boxmanbr** [ccloli/E-Hentai-Downloader#6]
Happened on the following galleries:

http://exhentai.org/g/578840/5be56fc56c/ pages 179 ~ 193
http://exhentai.org/g/730103/565ff88b66/ pages 014, 016
http://exhentai.org/g/415832/f59385369b/ pages 073 ~ 078

Downloaded 1.077 files (1.27GB) from other 31 galleries, they all are ok.

Logs and the error files:
https://mega.nz/#!ydETWCpQ!StRKzzsnDVafInKkt7sAOhQ8mo3X4edSatFCU5bO1HE

**Comment by ccloli** [comment]
Thanks for your feedback, I will check it tomorrow (you know, it's nearly 4AM in China), so please be patient and relax.:cat:
You can download failed files by yourself before the bug fixes.

**Comment by ccloli** [comment]
It probably caused by the image is not hosted on this server, or the GET variable "timestamp" is out of date. 

For the first one, you can change some characters of the image URL (so that the file of this URL is not exist) and load it, and it would show "An error has occurred. (403)".

For the second one, for example, the image URL of page http://exhentai.org/s/d343958104/844546-1 is http://122.116.91.2:48890/h/9d8e7093f8124708affaef6a2476d58dbec580cf-381798-1200-1697-jpg/keystamp=1440295500-4ed78ec613/_001.jpg 3 minutes ago, and when reloaded the page, the URL won't change. But 3 minutes later, the image URL was changed to http://122.116.91.2:48890/h/9d8e7093f8124708affaef6a2476d58dbec580cf-381798-1200-1697-jpg/keystamp=1440295800-68ae53e22b/_001.jpg, so I think not download it on time is another reason.

(By the way, the keystamp variables from different servers are different, this is another URL http://106.185.35.170:10358/h/9d8e7093f8124708affaef6a2476d58dbec580cf-381798-1200-1697-jpg/keystamp=1440295800-8fcc58cda1/_001.jpg)

The way to solve the problem is make the script to fetch that page again. I'll fix it right now. Thank you for your feedback.

**Comment by ccloli** [comment]
New version has been uploaded, please check if the bug is still exist.

**Comment by ccloli** [comment]
Yes, this bug is caused by out of time, now all the images' URL are not available and return "An error has occurred. (403)". So re-get the images' URL may fix this bug.

**Comment by Boxmanbr** [comment]
Many thanks.
