### ISSUE TITLE
Certain pages in a gallery won't download

### ISSUE THREAD

**Issue by ravenlord1** [ccloli/E-Hentai-Downloader#62]
In gallery https://exhentai.org/g/876783/7d60040806/ only some images download.  The images with simple names are fine.  The images with underscores in the name do not download.

I tried different setting regarding page numbering, range, etc and nothing helped.  The images with underscores in their name just got skipped after failing due to "network error".

Firefox 52.0.1
Windows 7 home premium SP1

**Comment by ccloli** [comment]
It works fine from my side. I noticed that the images with underscore are stitched images with two pages, maybe the file is too large and your network looks not so good, so that it downloads failed.

For large original images, EH will not distribute them to H@H network to save bandwidth and traffic. So when you accessing this image, you'll download them from EH origin servers, which is hosted in Holland. So that your connection to the server maybe slower than the website hosted in your country, it all depends on your ISP and the incoming/outcoming traffic of your country to Europe. 

You can try downloading failed image manually, just click the images on the gallery page, scroll down and you'll probably find a link named "Download original image" and click it. If the link doesn't show, the original image is the showing image.

Duplicate #61.

**Comment by ravenlord1** [comment]
I figured it out.  It has nothing to do with the size of the image or bandwidth issues.  It has to do with the way the script finds images.

When it scrapes an image at horizontal width 1280 or less, then it goes directly from the image on the screen to the download location.  For example, https://exhentai.org/s/533d5dc982/876783-2 links directly to http://46.166.148.168:4000/h/533d5dc98247efbb403235fe8eb9509968ac24ac-420942-1164-1639-jpg/keystamp=1490165700-098d1894c7;fileindex=43800236;xres=org/02.jpg

However, when it tries to scrape an image >1280 then it gets confused.  It can't get from the image on the screen to the original image because the image on the screen has been resized to 1280.  To get to the original image, it has to pass through another page first (token).  For example, https://exhentai.org/s/8e3b354ed2/876783-3 you first have to go to https://exhentai.org/fullimg.php?gid=876783&page=3&key=i49okwj8ve6 and then THAT goes to http://46.166.148.137/im/8e3b354ed2d9944715fcb462388c90b091f01c3b-619546-2325-1639-jpg/413934-bc3389794c7f203b1909cbcb6f50e340a39b8a3f/03_04.jpg?dl=1

The only way I found around this is to go to the advance options tab and select "Force download resized image (never download original image)".  This stops the app from looking for the original image, and instead just scrape the resized image on the screen.  For example, again https://exhentai.org/s/8e3b354ed2/876783-3 this time skips the hunt for the original and instead scrapes the resized image on the screen http://91.121.238.202:29354/h/44e95f6eaa0a8f9a40857440e6d64aedf9d4649d-146381-1280-902-jpg/keystamp=1490165700-b6ee4c41cf;fileindex=43800237;xres=1280/03_04.jpg

Hope this helps.  And thanks for a great product.  Perhaps on a to-do list, there will be a way to hunt the original images that have been resized down to 1280.  If not, then this is still a very powerful tool  :)
