### ISSUE TITLE
[Suggestion] Add a way to download original images >1280 horizontal

### ISSUE THREAD

**Issue by ravenlord1** [ccloli/E-Hentai-Downloader#63]
This is related to Issue #62 

I found that when the script scrapes an image at horizontal width 1280 or less, then it goes directly from the image on the screen to the download location. For example, https://exhentai.org/s/533d5dc982/876783-2 
links directly to http://46.166.148.168:4000/h/533d5dc98247efbb403235fe8eb9509968ac24ac-420942-1164-1639-jpg/keystamp=1490165700-098d1894c7;fileindex=43800236;xres=org/02.jpg

However, when it tries to scrape an image at width >1280 then the script gets confused. It can't get from the image on the screen to the original image because the image on the screen has been resized to 1280. To get to the original image, it has to pass through another page (token) first. For example, https://exhentai.org/s/8e3b354ed2/876783-3 
you first have to go to https://exhentai.org/fullimg.php?gid=876783&page=3&key=i49okwj8ve6 
and then THAT goes to http://46.166.148.137/im/8e3b354ed2d9944715fcb462388c90b091f01c3b-619546-2325-1639-jpg/413934-bc3389794c7f203b1909cbcb6f50e340a39b8a3f/03_04.jpg?dl=1
This confuses the script and it generates a network error after a few attempts.

The only way I found around this is to go to the advance options tab and select "Force download resized image (never download original image)". This stops the app from looking for the original image, and instead just has it scrape the resized image on the screen. For example, again https://exhentai.org/s/8e3b354ed2/876783-3 
this time skips the hunt for the original and instead scrapes the resized image on the screen http://91.121.238.202:29354/h/44e95f6eaa0a8f9a40857440e6d64aedf9d4649d-146381-1280-902-jpg/keystamp=1490165700-b6ee4c41cf;fileindex=43800237;xres=1280/03_04.jpg

Maybe there is a way to script navigation of the intermediate token page in able to scrape large originals?

**Comment by ccloli** [comment]
Yes, but not recommended, and not always the original image.

As mentioned, the image that links to the original image is hosted on E-Hentai origin servers, which hosted in Holland, Europe. So if your home is far away from it, you may have a low connection speed, and your browser or the server may drop the connection. For example, if you are in China, your connection will be cross HongKong, America, England, then last Holland, so that your connection is really slow.
![qq 20170329114404](https://cloud.githubusercontent.com/assets/8115912/24437778/a8937e46-1475-11e7-9951-6fd7818f839b.png)

But why the preview image (in the token page) loads so fast, that's because of the [Hentai@Home](https://e-hentai.org/hentaiathome.php) network, a P2P network that helps E-Hentai to split the traffic. When you load the image, it's not loaded from the origin servers, but a server that hosted H@H by some warm-hearted guys, so that the speed will not that slow.

Back to the topic, your question can be described as "How to load the original image from H@H server". The image has some specific hash tokens, that we don't know how to get it so that we CANNOT calculate the image URL. For example, the image of [your example](https://exhentai.org/s/8e3b354ed2/876783-3), the image URL is now: 
```
http://61.244.55.205:9595/h/44e95f6eaa0a8f9a40857440e6d64aedf9d4649d-146381-1280-902-jpg/keystamp=1490760600-d153256438;fileindex=43800237;xres=1280/03_04.jpg
```
if we just simply modify what we already know, like image size, it will be: 
```
http://61.244.55.205:9595/h/44e95f6eaa0a8f9a40857440e6d64aedf9d4649d-146381-2325-1639-jpg/keystamp=1490760600-d153256438;fileindex=43800237;xres=org/03_04.jpg
                                                                            ^^^^ ^^^^                                                            ^^^
```
and you can only see _An error has occurred. (403)_
In fact, the original image is:
```
http://220.132.129.131:9420/h/8e3b354ed2d9944715fcb462388c90b091f01c3b-619546-2325-1639-jpg/keystamp=1490760600-59e4a970b1;fileindex=43800237;xres=org/03_04.jpg
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^ ^^^^ ^^^^                         ^^^^^^^^^^                         ^^^
```
The file hash and keystamp hash are different from the 1280 one. Seems that the hash is also based on IP or some others, simply replace the modified part doesn't work.

The only possible way is to set a larger image size on your [E-Hentai](https://e-hentai.org/uconfig.php)/[ExHentai](https://exhentai.org/uconfig.php) setting. The largest size is 2400x, and the image that smaller than 2400x will show the original image through H@H network. However, it will cost more [image limits](https://github.com/ccloli/E-Hentai-Downloader/wiki/E%E2%88%92Hentai-Image-Viewing-Limits), even the image is 1200x or not that large, and you still can't make the image that larger than 2400x through H@H. Anyway, it's up to you :-)
![g6fc9 e ae6oho4 r e_k](https://cloud.githubusercontent.com/assets/8115912/24438627/1ee0ae20-147b-11e7-95ca-f72c452a91dc.png)

**Comment by ravenlord1** [comment]
OK, I see now.  Thank you for the excellent explanation.  This makes perfect sense now.  There is no way to know or guess the hash tokens. So that is that.

I tried adjusting the settings to 2400x for that gallery as you suggested and that indeed did work (no more network error!)  I just need to be careful with my image limits when I do that :)

Thanks again for a very sweet tool!
