### ISSUE TITLE
Temporary IP ban

### ISSUE THREAD

**Issue by hasawovow** [ccloli/E-Hentai-Downloader#84]
Recently got this message:

> Your IP address has been temporarily banned for excessive pageloads which indicates that you are using automated mirroring/harvesting software. The ban expires in X hours and Y minutes

I've been using the script without problems for over a year. From a bit of searching in the forums, it appears the message shows up when there's a "burst overload".

I'm not completely sure whether it's being caused by this script; if someone is sharing my IP, it could be them. It might also be from some other add-on/extension I have.

Do you know what the criteria for a "burst overload" are?  E.g. X page loads/requests over Y time? Have the criteria changed recently?

**Comment by ccloli** [comment]
I'm not sure, maybe that means you download too much images at the same time, like downloading multiple galleries or the multi-thread download settings is too big (like download 10+ images at the same time, <=5 is recommended). If your ISP is using a same public IP with many users (NAT), it would probably meet this problem. 

Sorry that I wasn't being banned before, so I cannot give you some advice, try reducing your frequency and download threads. Some others also report that his IP was banned, but looks like they are using proxy, so that they may using a shared IP to download images.

By the way, when your IP was banned, what does the response data looks like, like accessing to this [link](https://e-hentai.org/s/8f78284972/1033793-1) and this [link](https://e-hentai.org/fullimg.php?gid=1033793&page=1&key=srf4fyp8zqg)? Did they just shows a plain text that says:

> Your IP address has been temporarily banned for excessive pageloads which indicates that you are using automated mirroring/harvesting software. The ban expires in X hours and Y minutes

or showing an image that says your IP was banned?

**Comment by hasawovow** [comment]
Alright, just wanted to check if you'd encountered anything like it in the past. I've generally only downloaded 5 images at a time per tab, although I've had 2-3 tabs open downloading simultaneously. Haven't had problems with that before though.

It might be a tab management extension I have, I accidentally hit some weird key combination and it opened a lot of tabs simultaneously. I didn't think anything of it then, but if some of those were e-hentai tabs it might have triggered the IP ban. It also took a day for the ban to activate/message to appear, so they might be processed in batches at certain times during the day.

> By the way, when your IP was banned, what does the response data looks like, like accessing to this link and this link?

I get that same plaintext HTML message for both links (HTTP Status 200/OK). For the second link though, if I'm not logged in, I get redirected to a login page instead.

**Comment by ccloli** [comment]
Okay, thanks for your help. I usually set threads to 10 images and download 1~3 galleries at the same time, looks I'm lucky. So maybe the problem is on that extension, or maybe E-Hentai just set a more strict rules.

If your public IP is dynamic, re-connect to the Internet to get a new IP may pass the limit. Good luck.

**Comment by hasawovow** [comment]
The ban's expired/disappeared now, so it looks like I'm in the clear. Thanks for the fast replies, I'll close the issue and post an update if I get banned again.

**Comment by WangQiang102938** [comment]
EH itself will continue operating at least until the end of 2020 unless anything unexpected happens
不出意外的话EH会运营到2020年底（还有一年半，各位加油！）
