### ISSUE TITLE
You are not log in to E-Hentai Forums, so you can't download original image. Continue?

### ISSUE THREAD

**Issue by Faynwulf** [ccloli/E-Hentai-Downloader#90]
Whenever I try to download anything I get this message. The problem here is that I am logged into the forums.

**Comment by ccloli** [comment]
Hi, it works fine here. Maybe it's due to your cookie is not sync with E-Hentai forum. Please try this link https://e-hentai.org/s/cc13c28046/1161138-1 , and you'll see the link `Download original 2870 x 3950 3.29 MB source` at the bottom of the page, click that link and it'll redirect you to the login page.

If it gives you the image file, or redirect in a loop, please make sure that you've enabled cookie and also accept third-party cookie (https://github.com/ccloli/E-Hentai-Downloader/issues/86#issuecomment-353815914 says that if you don't enable third-party cookie, it may have some problems to download).

If you still get this message, please try clearing your cookie and try again. If it doesn't work, please press F12, choose Console tab, type `window.apiuid` and press Enter to confirm if it's grater than 0 instead of `-1`, and copy all the logs that started with `[EHD]` then paste them here.

**Comment by Faynwulf** [comment]
I should say that I only have those issues on exhentai and not on e-hentai.

**Comment by ccloli** [comment]
Okay, how about this link https://exhentai.org/s/cc13c28046/1161138-1 ? Is reset cookie and login again not working?

**Comment by Faynwulf** [comment]
Trying to download the picture gave me a white site with the text "err". I deleted my cookies and that fixed my issue completely. Thank you for your help!
