### ISSUE TITLE
Downloading big galleries creates a folder inside the zip

### ISSUE THREAD

**Issue by bluefiberbread** [ccloli/E-Hentai-Downloader#94]
Having the option to create folders disabled, it will sometimes create a folder with no name with the content of the gallery.

https://puu.sh/z5LPl/a23a9c551e.jpg

**Comment by ccloli** [comment]
Oops, I check my recent downloaded gallery, some of them also have a empty folder. It's a bug. Looks like JSZip treats `folder('')` as create empty folder sometimes. 

The bug should be fixed in next version. If you care about these zip files, from my test, they can be decompressed normally with most software like 7-Zip, WinRAR and WinZip (except Windows Explorer). If you just want to get the uncompressed files, decompress them with 7-Zip that you're using, and if you want to still get a standard zip file, compress them with 7-Zip again.
