### ISSUE TITLE
Support Guerilla Scripting 

### ISSUE THREAD

**Issue by Zero3K** [ccloli/E-Hentai-Downloader#96]
It would be nice if it could be made to work with the Guerilla Scripting addon (available at https://addons.palemoon.org/addon/guerilla-scripting/) that is useable by Pale Moon.

**Comment by ccloli** [comment]
Sorry I tried, but it seems that Guerilla Scripting has some unreasonable bugs, and they makes the script stop working. Also I can't debug with it, it doesn't throw any error, I can't use breakpoint to check what's going on, even `debugger` command is also not working. Sorry I give it up, maybe you can try [Greasemonkey for Pale Moon](https://github.com/janekptacijarabaci/greasemonkey/releases/tag/3.31Fork).

![image](https://user-images.githubusercontent.com/8115912/37863505-f94a1d1e-2f99-11e8-8521-e9c8ba19ed3c.png)
> I'm not sure why a variable assignment can be wrong and that `byteLength` is exist.

**Comment by Zero3K** [comment]
Have you tried checking the options that it has?

**Comment by Zero3K** [comment]
Have you tried looking at the Browser Console? I am able to get error info in the scripts that do work when I look at it.

**Comment by ccloli** [comment]
Did you mean the console that in the lower part of the picture? However I can't see any error info here. It just shows the previous messages before it stop working, and not showing any errors. 
![image](https://user-images.githubusercontent.com/8115912/37865791-8bec706e-2fbc-11e8-947a-b5092fa74b30.png)
(I'm not sure is that expression "in the lower part of" correct, I mean the area of red rectangle on the picture)

**Comment by Zero3K** [comment]
No, I mean the Browser Console accessible by pressing Ctrl+Shift+J.

**Comment by ccloli** [comment]
Okay, got it now. Sorry for the late reply, as I was revert my virtual machine back to some point and just reinstall the browser just now. 

Seems that Guerilla Scripting has some permission bugs, although I removed the related `GM_info` log that Guerilla Scripting doesn't support, it still denies me to access some critical parameters. 

So back to the first, I give up, it's the bug of Guerilla Scripting itself. If it doesn't allow me to access these values, the script won't work.

![image](https://user-images.githubusercontent.com/8115912/37866104-d516d2d0-2fc0-11e8-9e78-8cd64f29c54d.png)

**Comment by Zero3K** [comment]
What about the Security wrapper message?

**Comment by ccloli** [comment]
I checked [the GM_xhr source code of guerillascript](http://repo.or.cz/guerillascript.git/blob/HEAD:/main/modules/sbapi/xmlhttprequest.js), it exposed `response` property, so it should works fine, but I was denied to get `response.byteLength`. I Googled that error message, seems that it may happens when accessing cross-origin content, maybe Guerilla Scripting doesn't handle cross-origin content well?

> What about the Security wrapper message?

It says I cannot access `GM_info.scriptHandler` (also `GM_info.script` and so on), as it's not exposed those properties (from GM_xhr source code, you can see it exposes some properties by setting them on `__exposedProps__`). I checked [the source code about `GM_info`](http://repo.or.cz/guerillascript.git/blob/HEAD:/main/modules/sbapi/sandbox.js#l287), only got this:

```js
Object.defineProperty(sandbox, "GM_info", {
    get: tieto(null, function () { logError("GM_info(): stub!"); return {}; }),
});
```

Yes, `GM_info` is not supported by Guerilla Scripting, and it sets a useless getter (only to show the error) to prevent us to use some fallback ways. I tried passing it by self-creating a `GM_info`, but it also denied me.

So for the compatibility, I recommend you to use Greasemonkey for Pale Moon. Guerilla Scripting is not fully support GM function, and may have some unknown bugs (if it's GM compatible as it claims, everything should be fine), also its community environment is not as strong as Greasemonkey and other extensions -- not to say it's bad, it should be a thought work to write a extension like this, but for most compatibility, you should try a more stable solution.

**Comment by Zero3K** [comment]
Please try the new version he uploaded to https://addons.palemoon.org/addon/guerilla-scripting/.

**Comment by ccloli** [comment]
Yeah I noticed the new version when I was writing the previous comment. I just wanna to say the developer is nearly stop updating it (so am I :-( ) but I noticed it on its git repo (it says 15 minutes ago) so I deleted it soon. :smiling_imp: 

However I also have something want to write in the previous comment. I checked the source code of the newer version at that time, and it just exposed the `byteLength` property. But it doesn't make sense, that's not the main problem. Even though I remove all the code that uses `response.byteLength` it also throws an error on JSZip when converting that `response` to another type (maybe `Uint8Array` I guess). 

The main problem is not `byteLength` cannot be accessed, but **the data is cross-origined**, and Guerilla Scripting doesn't solve it as expected, it just send the data directly to the user script, and user script cannot read the data due to the same-origin security.

**Comment by ccloli** [comment]
BTW it's 2:40 AM in my timezone, it's time to sleep. If you have something new, just comment them here. I'm just noting that I cannot reply to you in a few hours, but I'll check them when I get up. Thank you. :stuck_out_tongue_closed_eyes:

**Comment by Zero3K** [comment]
Well, the developer of it doesn't want to get it to work with your script.

**Comment by ccloli** [comment]
Never mind, as most of the scripts don't need to use binary data, and the developer doesn't have reason to compatible with my script for just some uncommon use cases.
