### ISSUE TITLE
Get banned with limit of 3 at the same time

### ISSUE THREAD

**Issue by qiexie** [ccloli/E-Hentai-Downloader#98]
Could it be caused by fast network speed? If that is the case, is it okay to add an option to set wait time between each picture download?

Thank you.

**Comment by ccloli** [comment]
Not sure, but you might be right. Some people also said they were banned but they're using the script for a long time without being banned, so I said maybe it's due to like sharing IP or firewall rules. If you're using a shared IP address with others, you may also meet the problem. I'll try working on it, it should be in next version, thanks for your advice.

BTW, if your IP is dynamic (your IP changed each time when you reconnect to the network), you can bypass the banning by reconnect to the network.

**Comment by ccloli** [comment]
The feature is now on v1.30, you can config it at _Settings_ -> _Basic_ -> _Delay ... second(s) before requesting next image_. You can set the time by 0.1 second step.

Note that if you pause downloading when some image is not ready to request, the downloading list maybe not in order when you resume, because some of them are ticked when pausing so they are skipped, but the others not in pausing tick are not affected. The skipped images will be requested in next tick.
![image](https://user-images.githubusercontent.com/8115912/37895123-fd2db362-3112-11e8-9d8b-fbac331142db.png)

**Comment by qiexie** [comment]
Thank you very much! Both for the development and the improvement.
